import BezoutCounterexample.MainTheorem

/-!
# Section 6.4: countability and maximal ideals

This file formalizes Section 6.4 of the paper.

* `HasCountableCharacter A`: every nonzerodivisor of `A` belongs to at most countably many maximal
  ideals; in a domain the nonzerodivisors are the nonzero elements (`hasCountableCharacter_iff`).
* `IsSemihereditary A`: every finitely generated ideal is projective. Every Bézout domain is
  semihereditary (`IsBezout.isSemihereditary`), because each nonzero finitely generated ideal is
  principal and isomorphic to the ring.
* Couchot's theorem [Couchot, Theorem 12] (every semihereditary Bézout ring of countable character
  is an elementary divisor ring) is formalized only in the special case needed:
  `hasSmithNormalForm_of_hasCountableCharacter`, every `2 × 2` matrix over a Bézout domain of
  countable character has a Smith normal form.
* **Corollary 6.4** (`cor:not-countable-character`, `not_hasCountableCharacter`): `R` does not have
  countable character; some nonzero element of the countable ring `R` belongs to uncountably many
  maximal ideals.
* **The `2 × 2` consequence of [CS, Lemma 5.1]** (`hasSmithNormalForm_of_countable_firstRow`): a
  `2 × 2` matrix `F` over a Bézout domain `D` whose entries generate `D`, such that the ideal
  generated by its first row is contained in at most countably many maximal ideals, has a Smith
  normal form. The proof follows the paper: a column operation gives `F' = [[a, 0], [b, c]]`;
  [CS, Lemma 5.1] (`cs_lemma_5_1`) gives `p, q` with `(pa + qb) D + qc D = D`; then `(p, q)` is
  unimodular, completing it to an invertible matrix makes the first row `(pa + qb, qc)`
  unimodular, and further row and column operations give `diag(1, d)`. [CS, Lemma 5.1] itself is
  proved by the iterative argument of Chen–Sheibani and Fuchs–Salce (`reduction_step`,
  `lower_hasSmithNormalForm`: along an enumeration of the countably many maximal ideals containing
  the corner, the corner of a lower triangular matrix is repeatedly replaced by one generating a
  larger ideal, until it becomes a unit), after which `p, q` are read off from the resulting Smith
  normal form.
* `uncountable_maximal_ideals`: applied to `M`, and to the matrix obtained from `M` by
  interchanging both its rows and its columns, this shows that uncountably many maximal ideals of
  `R` contain `(1 + x, y)`, and uncountably many contain `(1 - x, y)`.
* The example `C = ℚ[t, z₁, z₂, …]` (`exampleC_*`): a countable domain with uncountably many
  distinct maximal ideals `𝔪_ε = (t, z₁ - ε₁, z₂ - ε₂, …)`, `ε ∈ {0, 1}^{ℕ>0}`, each with quotient
  `ℚ`, all containing the nonzero element `t`.
-/

noncomputable section

namespace BezoutCounterexample

open Matrix

/-! ## Countable character and semihereditary rings -/

section Definitions

variable (A : Type*) [CommRing A]

/-- A ring has *countable character* if every nonzerodivisor belongs to at most countably many
maximal ideals. -/
def HasCountableCharacter : Prop :=
  ∀ a ∈ nonZeroDivisors A, {𝔪 : Ideal A | 𝔪.IsMaximal ∧ a ∈ 𝔪}.Countable

/-- A ring is *semihereditary* if every finitely generated ideal is projective. -/
def IsSemihereditary : Prop := ∀ I : Ideal A, I.FG → Module.Projective A I

variable {A}

/-- A domain has countable character if and only if every nonzero element belongs to at most
countably many maximal ideals. -/
theorem hasCountableCharacter_iff [IsDomain A] :
    HasCountableCharacter A ↔
      ∀ a : A, a ≠ 0 → {𝔪 : Ideal A | 𝔪.IsMaximal ∧ a ∈ 𝔪}.Countable := by
  simp only [HasCountableCharacter, mem_nonZeroDivisors_iff_ne_zero]

/-- Every Bézout domain is semihereditary, because each nonzero finitely generated ideal is
principal and isomorphic to the ring. -/
theorem IsBezout.isSemihereditary [IsDomain A] [IsBezout A] : IsSemihereditary A := by
  intro I hI
  obtain ⟨g, hg⟩ := (IsBezout.isPrincipal_of_FG I hI).principal
  by_cases h0 : g = 0
  · have : I = ⊥ := by rw [hg, h0]; simp
    subst this
    exact Module.Projective.of_free
  · have e : A ≃ₗ[A] (Submodule.span A {g}) := LinearEquiv.toSpanNonzeroSingleton A A g h0
    rw [hg]
    exact Module.Projective.of_equiv e

end Definitions

/-! ## Equivalence of matrices -/

section Equiv

variable {D : Type*} [CommRing D] {m n : ℕ}

lemma MatrixEquivalent.refl (F : Matrix (Fin m) (Fin n) D) : MatrixEquivalent F F :=
  ⟨1, 1, by simp⟩

lemma MatrixEquivalent.trans {F G H : Matrix (Fin m) (Fin n) D} (h1 : MatrixEquivalent F G)
    (h2 : MatrixEquivalent G H) : MatrixEquivalent F H := by
  obtain ⟨P, Q, rfl⟩ := h1
  obtain ⟨P', Q', rfl⟩ := h2
  refine ⟨P' * P, Q * Q', ?_⟩
  simp only [Units.val_mul, Matrix.mul_assoc]

lemma MatrixEquivalent.mul_left {F : Matrix (Fin m) (Fin n) D} (P : GL (Fin m) D) :
    MatrixEquivalent F ((P : Matrix (Fin m) (Fin m) D) * F) :=
  ⟨P, 1, by simp⟩

lemma MatrixEquivalent.mul_right {F : Matrix (Fin m) (Fin n) D} (Q : GL (Fin n) D) :
    MatrixEquivalent F (F * (Q : Matrix (Fin n) (Fin n) D)) :=
  ⟨1, Q, by simp⟩

lemma HasSmithNormalForm.of_equiv {F G : Matrix (Fin m) (Fin n) D} (h : MatrixEquivalent F G)
    (hG : HasSmithNormalForm G) : HasSmithNormalForm F := by
  obtain ⟨H, hGH, hH⟩ := hG
  exact ⟨H, h.trans hGH, hH⟩

/-- The transpose of an invertible matrix. -/
def glTranspose (P : GL (Fin n) D) : GL (Fin n) D :=
  ⟨(P : Matrix (Fin n) (Fin n) D)ᵀ, ((P⁻¹ : GL (Fin n) D) : Matrix (Fin n) (Fin n) D)ᵀ, by
    rw [← transpose_mul, ← Units.val_mul, inv_mul_cancel, Units.val_one, transpose_one], by
    rw [← transpose_mul, ← Units.val_mul, mul_inv_cancel, Units.val_one, transpose_one]⟩

lemma IsSmithNormalForm.transpose {G : Matrix (Fin m) (Fin n) D} (h : IsSmithNormalForm G) :
    IsSmithNormalForm Gᵀ := by
  rw [isSmithNormalForm_iff_chain] at h ⊢
  obtain ⟨d, hd, hdiv⟩ := h
  refine ⟨d, fun i j => ?_, fun k hk => hdiv k (by rw [min_comm]; exact hk)⟩
  rw [transpose_apply, hd]
  by_cases h : (j : ℕ) = (i : ℕ)
  · simp [h]
  · simp [h, Ne.symm h]

lemma HasSmithNormalForm.of_transpose {F : Matrix (Fin m) (Fin n) D}
    (h : HasSmithNormalForm Fᵀ) : HasSmithNormalForm F := by
  obtain ⟨G, ⟨P, Q, hPQ⟩, hG⟩ := h
  refine ⟨Gᵀ, ⟨glTranspose Q, glTranspose P, ?_⟩, hG.transpose⟩
  rw [← hPQ]
  simp only [glTranspose, Units.val_mk, transpose_mul, transpose_transpose, Matrix.mul_assoc]

/-- Smith normal forms survive scaling by a common factor. -/
lemma HasSmithNormalForm.smul {F : Matrix (Fin m) (Fin n) D} (h : HasSmithNormalForm F) (g : D) :
    HasSmithNormalForm (g • F) := by
  obtain ⟨G, ⟨P, Q, hPQ⟩, hG⟩ := h
  obtain ⟨d, hd, hdiv⟩ := (isSmithNormalForm_iff_chain G).1 hG
  refine ⟨g • G, ⟨P, Q, ?_⟩, (isSmithNormalForm_iff_chain _).2
    ⟨fun k => g * d k, fun i j => ?_, fun k hk => mul_dvd_mul_left g (hdiv k hk)⟩⟩
  · rw [Matrix.mul_smul, Matrix.smul_mul, hPQ]
  · rw [Matrix.smul_apply, hd, smul_eq_mul]
    split_ifs <;> simp

/-- The entries of `F` generate the ring: no proper ideal contains all entries of `F`. -/
def EntriesGenerate (F : Matrix (Fin m) (Fin n) D) : Prop :=
  ∀ I : Ideal D, (∀ i j, F i j ∈ I) → I = ⊤

/-- Multiplication by invertible matrices on either side preserves the ideal generated by all
matrix entries. -/
lemma EntriesGenerate.equiv {F G : Matrix (Fin m) (Fin n) D} (hF : EntriesGenerate F)
    (h : MatrixEquivalent F G) : EntriesGenerate G := by
  intro I hI
  exact hF I (h.entry_mem I hI)

lemma EntriesGenerate.transpose {F : Matrix (Fin m) (Fin n) D} (hF : EntriesGenerate F) :
    EntriesGenerate Fᵀ :=
  fun I hI => hF I fun i j => hI j i

end Equiv

/-! ## Elementary operations over a Bézout domain -/

section Bezout2

variable {D : Type*} [CommRing D] [IsDomain D] [IsBezout D]

/-- **Bézout data**: `a = a' g`, `b = b' g` and `r a' + s b' = 1` (so `g = r a + s b` generates
`(a, b)`). -/
lemma exists_bezout_data (a b : D) :
    ∃ r s a' b' g : D, a = a' * g ∧ b = b' * g ∧ r * a' + s * b' = 1 := by
  obtain ⟨g, hg⟩ := (IsBezout.iff_span_pair_isPrincipal.1 inferInstance a b).principal
  by_cases h0 : g = 0
  · have ha : a ∈ Ideal.span {a, b} := Ideal.subset_span (by simp)
    have hb : b ∈ Ideal.span {a, b} := Ideal.subset_span (by simp)
    rw [hg, h0, Submodule.span_singleton_eq_bot.2 rfl, Submodule.mem_bot] at ha hb
    exact ⟨1, 0, 1, 0, 0, by simp [ha], by simp [hb], by ring⟩
  · have hgmem : g ∈ Ideal.span {a, b} := by rw [hg]; exact Submodule.mem_span_singleton_self g
    obtain ⟨r, s, hrs⟩ := Ideal.mem_span_pair.1 hgmem
    have ha : a ∈ D ∙ g := by rw [← hg]; exact Ideal.subset_span (by simp)
    have hb : b ∈ D ∙ g := by rw [← hg]; exact Ideal.subset_span (by simp)
    obtain ⟨a', ha'⟩ := Submodule.mem_span_singleton.1 ha
    obtain ⟨b', hb'⟩ := Submodule.mem_span_singleton.1 hb
    rw [smul_eq_mul] at ha' hb'
    refine ⟨r, s, a', b', g, ha'.symm, hb'.symm, ?_⟩
    have : (r * a' + s * b') * g = 1 * g := by
      rw [one_mul, add_mul, mul_assoc, mul_assoc, ha', hb', hrs]
    exact mul_right_cancel₀ h0 this

variable (D) in
/-- The invertible matrix `[[r, s], [-b', a']]` of Bézout data `r a' + s b' = 1`. -/
def gl2 (r s a' b' : D) (h : r * a' + s * b' = 1) : GL (Fin 2) D :=
  ⟨!![r, s; -b', a'], !![a', -s; b', r], by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;>
      first | linear_combination h | linear_combination -h | ring, by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;>
      first | linear_combination h | linear_combination -h | ring⟩

omit [IsDomain D] [IsBezout D] in
@[simp] lemma gl2_val (r s a' b' : D) (h : r * a' + s * b' = 1) :
    ((gl2 D r s a' b' h : GL (Fin 2) D) : Matrix (Fin 2) (Fin 2) D) = !![r, s; -b', a'] := rfl

variable (D) in
/-- The column operation "add column 1 to column 0". -/
def glAddCol : GL (Fin 2) D :=
  ⟨!![1, 0; 1, 1], !![1, 0; -1, 1], by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two], by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two]⟩

variable (D) in
/-- The permutation matrix interchanging the two rows (or columns). -/
def glSwap : GL (Fin 2) D :=
  ⟨!![0, 1; 1, 0], !![0, 1; 1, 0], by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two], by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two]⟩

omit [IsDomain D] [IsBezout D] in
/-- A lower triangular matrix with a unit in the corner has a Smith normal form `diag(1, d)`. -/
lemma hasSmithNormalForm_of_isUnit_corner (N : Matrix (Fin 2) (Fin 2) D) (hN : N 0 1 = 0)
    (hu : IsUnit (N 0 0)) : HasSmithNormalForm N := by
  obtain ⟨u, hu⟩ := hu
  set P : GL (Fin 2) D := ⟨!![(u⁻¹ : Dˣ), 0; -(N 1 0) * (u⁻¹ : Dˣ), 1], !![(u : D), 0; N 1 0, 1],
    by ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two],
    by ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two]⟩
  refine ⟨!![1, 0; 0, N 1 1], ⟨P, 1, ?_⟩, (isSmithNormalForm_iff_chain _).2
    ⟨fun k => if k = 0 then 1 else N 1 1, fun i j => ?_, fun k hk => ?_⟩⟩
  · ext i j
    fin_cases i <;> fin_cases j <;>
      simp [P, Matrix.mul_apply, Fin.sum_univ_two, Matrix.vecMul, dotProduct, hN, ← hu]
  · fin_cases i <;> fin_cases j <;> simp
  · have hk0 : k = 0 := by simp at hk; omega
    subst hk0
    simp

/-- Column Hermite reduction of the first row of a `2 × 2` matrix: an invertible column operation
sends the first row `(F₀₀, F₀₁)` to `(g, 0)`, where `g D = (F₀₀, F₀₁) D`. -/
lemma exists_col_reduce (N : Matrix (Fin 2) (Fin 2) D) :
    ∃ (Q : GL (Fin 2) D) (g : D), (N * (Q : Matrix (Fin 2) (Fin 2) D)) 0 0 = g ∧
      (N * (Q : Matrix (Fin 2) (Fin 2) D)) 0 1 = 0 ∧
      Ideal.span {g} = (Ideal.span {N 0 0, N 0 1} : Ideal D) ∧
      (N 1 0 = 0 → N 1 1 = 0 → (N * (Q : Matrix (Fin 2) (Fin 2) D)) 1 0 = 0 ∧
        (N * (Q : Matrix (Fin 2) (Fin 2) D)) 1 1 = 0) := by
  obtain ⟨r, s, a', b', g, ha, hb, hrs⟩ := exists_bezout_data (N 0 0) (N 0 1)
  refine ⟨glTranspose (gl2 D r s a' b' hrs), g, ?_, ?_, ?_, fun h10 h11 => ⟨?_, ?_⟩⟩
  · simp [glTranspose, Matrix.mul_apply, Fin.sum_univ_two]
    rw [ha, hb]; linear_combination g * hrs
  · simp [glTranspose, Matrix.mul_apply, Fin.sum_univ_two]
    rw [ha, hb]; ring
  · apply le_antisymm
    · rw [Ideal.span_singleton_le_iff_mem]
      have hg : g = r * N 0 0 + s * N 0 1 := by rw [ha, hb]; linear_combination -g * hrs
      rw [hg]
      exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp)))
        (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp)))
    · rw [Ideal.span_le]
      rintro z (rfl | rfl)
      · rw [ha]; exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self g)
      · rw [hb]; exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self g)
  · simp [glTranspose, Matrix.mul_apply, Fin.sum_univ_two, h10, h11]
  · simp [glTranspose, Matrix.mul_apply, Fin.sum_univ_two, h10, h11]

end Bezout2

/-! ## [CS, Lemma 5.1]: the iterative argument -/

section Iteration

variable {D : Type*} [CommRing D] [IsDomain D] [IsBezout D]

/-- **The reduction step** (Chen–Sheibani, Lemma 5.1; Fuchs–Salce III.6.5): from a lower
triangular matrix whose entries generate `D`, produce another one (up to equivalence and
transposition) whose corner generates a larger ideal and avoids the given maximal ideal `𝔪`. -/
lemma reduction_step (N : Matrix (Fin 2) (Fin 2) D) (hN : N 0 1 = 0) (hu : EntriesGenerate N)
    (𝔪 : Ideal D) (h𝔪 : 𝔪.IsMaximal) :
    ∃ N' : Matrix (Fin 2) (Fin 2) D, (HasSmithNormalForm N' → HasSmithNormalForm N) ∧
      N' 0 1 = 0 ∧ EntriesGenerate N' ∧ N' 0 0 ∉ 𝔪 ∧
      Ideal.span {N 0 0} ≤ Ideal.span {N' 0 0} := by
  classical
  -- first make the entry below the corner avoid `𝔪` when needed
  obtain ⟨N₁, hNN₁, h00, h01, h10mem, h11⟩ : ∃ N₁ : Matrix (Fin 2) (Fin 2) D,
      MatrixEquivalent N N₁ ∧ N₁ 0 0 = N 0 0 ∧ N₁ 0 1 = 0 ∧
      (N 0 0 ∈ 𝔪 → N₁ 1 0 ∉ 𝔪) ∧ N₁ 1 1 = N 1 1 := by
    by_cases hb : N 1 0 ∈ 𝔪
    · refine ⟨N * (glAddCol D : Matrix (Fin 2) (Fin 2) D), MatrixEquivalent.mul_right _, ?_, ?_,
        fun ha h => ?_, ?_⟩
      · simp [glAddCol, Matrix.mul_apply, Fin.sum_univ_two, hN]
      · simp [glAddCol, Matrix.mul_apply, Fin.sum_univ_two, hN]
      · have hc : N 1 1 ∈ 𝔪 := by
          have : (N * (glAddCol D : Matrix (Fin 2) (Fin 2) D)) 1 0 = N 1 0 + N 1 1 := by
            simp [glAddCol, Matrix.mul_apply, Fin.sum_univ_two]
          rw [this] at h
          have := 𝔪.sub_mem h hb
          rwa [add_sub_cancel_left] at this
        apply h𝔪.ne_top
        apply hu 𝔪
        intro i j
        fin_cases i <;> fin_cases j
        · exact ha
        · simp only [Fin.zero_eta, Fin.mk_one]; rw [hN]; exact 𝔪.zero_mem
        · exact hb
        · exact hc
      · simp [glAddCol, Matrix.mul_apply, Fin.sum_univ_two]
    · exact ⟨N, MatrixEquivalent.refl N, rfl, hN, fun _ => hb, rfl⟩
  -- the Hermite reduction of the first column
  obtain ⟨r, s, a', b', g, ha, hb, hrs⟩ := exists_bezout_data (N₁ 0 0) (N₁ 1 0)
  set U := ((gl2 D r s a' b' hrs : GL (Fin 2) D) : Matrix (Fin 2) (Fin 2) D) * N₁ with hU
  have hU00 : U 0 0 = g := by
    simp only [hU, gl2_val, Matrix.mul_apply, Fin.sum_univ_two]
    simp; rw [ha, hb]; linear_combination g * hrs
  have hU10 : U 1 0 = 0 := by
    simp only [hU, gl2_val, Matrix.mul_apply, Fin.sum_univ_two]
    simp; rw [ha, hb]; ring
  refine ⟨Uᵀ, fun h => ?_, ?_, ?_, ?_, ?_⟩
  · exact HasSmithNormalForm.of_equiv hNN₁
      (HasSmithNormalForm.of_equiv (MatrixEquivalent.mul_left _) h.of_transpose)
  · rw [transpose_apply]; exact hU10
  · exact ((hu.equiv hNN₁).equiv (MatrixEquivalent.mul_left _)).transpose
  · rw [transpose_apply, hU00]
    intro hg
    by_cases ha0 : N 0 0 ∈ 𝔪
    · apply h10mem ha0
      rw [hb]; exact 𝔪.mul_mem_left _ hg
    · apply ha0
      rw [← h00, ha]; exact 𝔪.mul_mem_left _ hg
  · rw [transpose_apply, hU00, Ideal.span_singleton_le_span_singleton, ← h00, ha]
    exact dvd_mul_left g a'

/-- Lower triangular `2 × 2` matrices whose entries generate `D`. -/
abbrev LowerGen (D : Type*) [CommRing D] :=
  {N : Matrix (Fin 2) (Fin 2) D // N 0 1 = 0 ∧ EntriesGenerate N}

/-- One reduction step, chosen. -/
def stepLower (N : LowerGen D) (𝔪 : Ideal D) (h𝔪 : 𝔪.IsMaximal) : LowerGen D :=
  ⟨Classical.choose (reduction_step N.1 N.2.1 N.2.2 𝔪 h𝔪),
    (Classical.choose_spec (reduction_step N.1 N.2.1 N.2.2 𝔪 h𝔪)).2.1,
    (Classical.choose_spec (reduction_step N.1 N.2.1 N.2.2 𝔪 h𝔪)).2.2.1⟩

lemma stepLower_spec (N : LowerGen D) (𝔪 : Ideal D) (h𝔪 : 𝔪.IsMaximal) :
    (HasSmithNormalForm (stepLower N 𝔪 h𝔪).1 → HasSmithNormalForm N.1) ∧
      (stepLower N 𝔪 h𝔪).1 0 0 ∉ 𝔪 ∧
      Ideal.span {N.1 0 0} ≤ Ideal.span {(stepLower N 𝔪 h𝔪).1 0 0} :=
  ⟨(Classical.choose_spec (reduction_step N.1 N.2.1 N.2.2 𝔪 h𝔪)).1,
    (Classical.choose_spec (reduction_step N.1 N.2.1 N.2.2 𝔪 h𝔪)).2.2.2.1,
    (Classical.choose_spec (reduction_step N.1 N.2.1 N.2.2 𝔪 h𝔪)).2.2.2.2⟩

/-- The sequence of reductions along an enumeration `f` of maximal ideals. -/
def seqLower (N₀ : LowerGen D) (f : ℕ → Ideal D) (hf : ∀ k, (f k).IsMaximal) : ℕ → LowerGen D
  | 0 => N₀
  | k + 1 => stepLower (seqLower N₀ f hf k) (f k) (hf k)

/-- **Diagonal reduction of lower triangular matrices** whose corner lies in only countably many
maximal ideals: iterating the reduction step along an enumeration `𝔪₁, 𝔪₂, …` of these maximal
ideals, the union of the corner ideals is not proper (a maximal ideal containing it would be some
`𝔪ₖ`, which the `k`-th corner avoids), so some corner is a unit. -/
theorem lower_hasSmithNormalForm (N : Matrix (Fin 2) (Fin 2) D) (hN : N 0 1 = 0)
    (hu : EntriesGenerate N) (hcount : {𝔪 : Ideal D | 𝔪.IsMaximal ∧ N 0 0 ∈ 𝔪}.Countable) :
    HasSmithNormalForm N := by
  classical
  by_cases hne : {𝔪 : Ideal D | 𝔪.IsMaximal ∧ N 0 0 ∈ 𝔪}.Nonempty
  · obtain ⟨f, hf⟩ := hcount.exists_eq_range hne
    have hfmax : ∀ k, (f k).IsMaximal := fun k => by
      have : f k ∈ {𝔪 : Ideal D | 𝔪.IsMaximal ∧ N 0 0 ∈ 𝔪} := by rw [hf]; exact ⟨k, rfl⟩
      exact this.1
    set N₀ : LowerGen D := ⟨N, hN, hu⟩
    set S := seqLower N₀ f hfmax
    have hSsucc : ∀ k, S (k + 1) = stepLower (S k) (f k) (hfmax k) := fun k => rfl
    have hmono : Monotone fun k => Ideal.span {(S k).1 0 0} := by
      refine monotone_nat_of_le_succ fun k => ?_
      rw [hSsucc]; exact (stepLower_spec _ _ _).2.2
    -- some corner is a unit
    have hunit : ∃ k, IsUnit ((S k).1 0 0) := by
      by_contra hcon
      push Not at hcon
      set I := ⨆ k, Ideal.span {(S k).1 0 0}
      have hmem : ∀ z, z ∈ I ↔ ∃ k, z ∈ Ideal.span {(S k).1 0 0} := fun z =>
        Submodule.mem_iSup_of_directed _ hmono.directed_le
      have hI : I ≠ ⊤ := by
        intro h
        obtain ⟨k, hk⟩ := (hmem 1).1 (h ▸ Submodule.mem_top)
        exact hcon k (Ideal.span_singleton_eq_top.1 ((Ideal.eq_top_iff_one _).2 hk))
      obtain ⟨J, hJ, hIJ⟩ := Ideal.exists_le_maximal I hI
      have hNJ : N 0 0 ∈ J := hIJ ((hmem _).2 ⟨0, Ideal.mem_span_singleton_self _⟩)
      have hJS : J ∈ {𝔪 : Ideal D | 𝔪.IsMaximal ∧ N 0 0 ∈ 𝔪} := ⟨hJ, hNJ⟩
      rw [hf] at hJS
      obtain ⟨k, rfl⟩ := hJS
      have h1 := (stepLower_spec (S k) (f k) (hfmax k)).2.1
      rw [← hSsucc] at h1
      exact h1 (hIJ ((hmem _).2 ⟨k + 1, Ideal.mem_span_singleton_self _⟩))
    obtain ⟨k, hk⟩ := hunit
    have hback : ∀ k, HasSmithNormalForm (S k).1 → HasSmithNormalForm N := by
      intro k
      induction k with
      | zero => exact id
      | succ k ih =>
        intro h
        rw [hSsucc] at h
        exact ih ((stepLower_spec _ _ _).1 h)
    exact hback k (hasSmithNormalForm_of_isUnit_corner _ (S k).2.1 hk)
  · -- no maximal ideal contains the corner: it is a unit
    have hunit : IsUnit (N 0 0) := by
      by_contra hnu
      have hne' : Ideal.span {N 0 0} ≠ ⊤ := fun h => hnu (Ideal.span_singleton_eq_top.1 h)
      obtain ⟨𝔪, h𝔪, hle⟩ := Ideal.exists_le_maximal _ hne'
      exact hne ⟨𝔪, h𝔪, hle (Ideal.mem_span_singleton_self _)⟩
    exact hasSmithNormalForm_of_isUnit_corner N hN hunit

omit [IsDomain D] [IsBezout D] in
/-- If the entries of a `2 × 2` matrix generate the ring and `P F Q = diag(d₁, d₂)` is a Smith
normal form, then `d₁ = (P F Q)₀₀` is a unit. -/
lemma exists_isUnit_of_hasSmithNormalForm {F : Matrix (Fin 2) (Fin 2) D}
    (hF : EntriesGenerate F) (h : HasSmithNormalForm F) :
    ∃ P Q : GL (Fin 2) D,
      IsUnit (((P : Matrix (Fin 2) (Fin 2) D) * F * (Q : Matrix (Fin 2) (Fin 2) D)) 0 0) := by
  obtain ⟨G, hFG, hG⟩ := h
  obtain ⟨d, hd, hdiv⟩ := (isSmithNormalForm_iff_chain G).1 hG
  obtain ⟨c, hc⟩ := hdiv 0 (by norm_num)
  have hGmem : ∀ i j, G i j ∈ (Ideal.span {d 0} : Ideal D) := by
    intro i j
    fin_cases i <;> fin_cases j <;> rw [hd] <;> simp [hc, Ideal.mem_span_singleton]
  have htop := hF _ (hFG.entry_mem _ hGmem)
  obtain ⟨P, Q, hPQ⟩ := hFG
  refine ⟨P, Q, ?_⟩
  rw [hPQ, hd]
  simpa [Ideal.span_singleton_eq_top] using htop

/-- **[CS, Lemma 5.1]**, in the form used in the paper. Let `D` be a Bézout domain and let
`a, b, c ∈ D` with `aD + bD + cD = D`, such that `a` lies in at most countably many maximal ideals.
Then there are `p, q ∈ D` with `(pa + qb) D + qc D = D`.

(Proof: the iterative argument `lower_hasSmithNormalForm` gives a Smith normal form
`P [[a, 0], [b, c]] Q = diag(d₁, d₂)` with `d₁` a unit, and `(p, q)` is the first row of `P`.) -/
theorem cs_lemma_5_1 (a b c : D) (habc : Ideal.span {a, b, c} = ⊤)
    (hcount : {𝔪 : Ideal D | 𝔪.IsMaximal ∧ a ∈ 𝔪}.Countable) :
    ∃ p q : D, Ideal.span {p * a + q * b, q * c} = ⊤ := by
  have hgen : EntriesGenerate !![a, 0; b, c] := by
    intro I hI
    rw [eq_top_iff, ← habc, Ideal.span_le]
    rintro z (rfl | rfl | rfl)
    · simpa using hI 0 0
    · simpa using hI 1 0
    · simpa using hI 1 1
  obtain ⟨P, Q, hPQ⟩ := exists_isUnit_of_hasSmithNormalForm hgen
    (lower_hasSmithNormalForm _ rfl hgen (by simpa using hcount))
  refine ⟨(P : Matrix (Fin 2) (Fin 2) D) 0 0, (P : Matrix (Fin 2) (Fin 2) D) 0 1, ?_⟩
  refine Ideal.eq_top_of_isUnit_mem _ ?_ hPQ
  have e : ((P : Matrix (Fin 2) (Fin 2) D) * !![a, 0; b, c] * Q) 0 0 =
      ((P : Matrix (Fin 2) (Fin 2) D) 0 0 * a + (P : Matrix (Fin 2) (Fin 2) D) 0 1 * b) *
        (Q : Matrix (Fin 2) (Fin 2) D) 0 0 +
      ((P : Matrix (Fin 2) (Fin 2) D) 0 1 * c) * (Q : Matrix (Fin 2) (Fin 2) D) 1 0 := by
    simp [Matrix.mul_apply, Fin.sum_univ_two]
  rw [e]
  exact Ideal.add_mem _ (Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp)))
    (Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp)))

/-- **The `2 × 2` consequence of [CS, Lemma 5.1].** Let `F` be a `2 × 2` matrix over a Bézout
domain `D` whose entries generate `D`, and suppose that the ideal generated by its first row is
contained in at most countably many maximal ideals. Then `F` has a Smith normal form.

Proof (as in the paper): an invertible column operation sends the first row of `F` to `(a, 0)`,
where `a D` is the ideal generated by that row, so `F` is equivalent to `F' = [[a, 0], [b, c]]`
with `aD + bD + cD = D`. [CS, Lemma 5.1] gives `p, q` with `(pa + qb) D + qc D = D`; necessarily
`pD + qD = D`. Completing `(p, q)` to the first row of an invertible matrix makes the first row of
`F'` equal to the unimodular row `(pa + qb, qc)`; an invertible column operation changes it to
`(1, 0)`, and a final row operation yields `diag(1, d)`. -/
theorem hasSmithNormalForm_of_countable_firstRow (F : Matrix (Fin 2) (Fin 2) D)
    (hF : EntriesGenerate F)
    (hcount : {𝔪 : Ideal D | 𝔪.IsMaximal ∧ Ideal.span {F 0 0, F 0 1} ≤ 𝔪}.Countable) :
    HasSmithNormalForm F := by
  -- an invertible column operation sends the first row to `(a, 0)`
  obtain ⟨Q₁, a, hF'00, hF'01, hspan, -⟩ := exists_col_reduce F
  set F' := F * (Q₁ : Matrix (Fin 2) (Fin 2) D) with hF'
  refine HasSmithNormalForm.of_equiv (MatrixEquivalent.mul_right Q₁) ?_
  have hF'gen : EntriesGenerate F' := hF.equiv (MatrixEquivalent.mul_right Q₁)
  -- `aD + bD + cD = D`
  have habc : Ideal.span {a, F' 1 0, F' 1 1} = ⊤ := by
    apply hF'gen
    intro i j
    fin_cases i <;> fin_cases j
    · rw [show (⟨0, _⟩ : Fin 2) = 0 from rfl, hF'00]; exact Ideal.subset_span (by simp)
    · rw [show (⟨0, _⟩ : Fin 2) = 0 from rfl, show (⟨1, _⟩ : Fin 2) = 1 from rfl, hF'01]
      exact Ideal.zero_mem _
    · exact Ideal.subset_span (by simp)
    · exact Ideal.subset_span (by simp)
  -- the maximal ideals containing `a` are those containing the first row of `F`
  have hcount' : {𝔪 : Ideal D | 𝔪.IsMaximal ∧ a ∈ 𝔪}.Countable := by
    refine hcount.mono ?_
    rintro 𝔪 ⟨h𝔪, ha𝔪⟩
    refine ⟨h𝔪, ?_⟩
    rw [← hspan, Ideal.span_le, Set.singleton_subset_iff]
    exact ha𝔪
  -- [CS, Lemma 5.1]
  obtain ⟨p, q, hpq⟩ := cs_lemma_5_1 a (F' 1 0) (F' 1 1) habc hcount'
  -- necessarily `pD + qD = D`
  have hpq' : Ideal.span {p, q} = (⊤ : Ideal D) := by
    by_contra hne
    obtain ⟨𝔫, h𝔫, hle⟩ := Ideal.exists_le_maximal _ hne
    have hp : p ∈ 𝔫 := hle (Ideal.subset_span (by simp))
    have hq : q ∈ 𝔫 := hle (Ideal.subset_span (by simp))
    apply h𝔫.ne_top
    rw [eq_top_iff, ← hpq, Ideal.span_le]
    rintro z (rfl | rfl)
    · exact 𝔫.add_mem (𝔫.mul_mem_right _ hp) (𝔫.mul_mem_right _ hq)
    · exact 𝔫.mul_mem_right _ hq
  -- complete `(p, q)` to the first row of an invertible matrix `P = [[p, q], [-s, r]]`
  obtain ⟨r, s, hrs⟩ : ∃ r s : D, r * p + s * q = 1 := by
    obtain ⟨r, s, h⟩ := Ideal.mem_span_pair.1 ((Ideal.eq_top_iff_one _).1 hpq')
    exact ⟨r, s, h⟩
  let P : GL (Fin 2) D := ⟨!![p, q; -s, r], !![r, -q; s, p], by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;>
      first | linear_combination hrs | ring, by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;>
      first | linear_combination hrs | ring⟩
  refine HasSmithNormalForm.of_equiv (MatrixEquivalent.mul_left P) ?_
  -- the first row of `P F'` is the unimodular row `(pa + qb, qc)`
  set F'' := (P : Matrix (Fin 2) (Fin 2) D) * F' with hF''
  have h00 : F'' 0 0 = p * a + q * F' 1 0 := by
    simp [hF'', P, Matrix.vecMul, dotProduct, Fin.sum_univ_two, hF'00]
  have h01 : F'' 0 1 = q * F' 1 1 := by
    simp [hF'', P, Matrix.vecMul, dotProduct, Fin.sum_univ_two, hF'01]
  -- an invertible column operation changes it to `(1, 0)`
  obtain ⟨u, v, huv⟩ : ∃ u v : D, u * F'' 0 0 + v * F'' 0 1 = 1 := by
    rw [h00, h01]
    obtain ⟨u, v, h⟩ := Ideal.mem_span_pair.1 ((Ideal.eq_top_iff_one _).1 hpq)
    exact ⟨u, v, h⟩
  let Q : GL (Fin 2) D := ⟨!![u, -F'' 0 1; v, F'' 0 0], !![F'' 0 0, F'' 0 1; -v, u], by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;>
      first | linear_combination huv | ring, by
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;>
      first | linear_combination huv | ring⟩
  refine HasSmithNormalForm.of_equiv (MatrixEquivalent.mul_right Q) ?_
  -- and a final row operation yields `diag(1, d)`
  apply hasSmithNormalForm_of_isUnit_corner
  · simp [Q, Matrix.mul_apply, Fin.sum_univ_two]
    ring
  · have : (F'' * (Q : Matrix (Fin 2) (Fin 2) D)) 0 0 = 1 := by
      simp [Q, Matrix.mul_apply, Fin.sum_univ_two]
      linear_combination huv
    rw [this]
    exact isUnit_one

/-- **Couchot's theorem, in the special case needed** (`2 × 2` matrices over domains): over a
Bézout domain of countable character, every `2 × 2` matrix has a Smith normal form.

We divide out the ideal generated by the entries (principal, as `D` is Bézout), make sure the first
row is nonzero (interchanging the rows if necessary), and apply the `2 × 2` consequence of
[CS, Lemma 5.1]: the first row generates a nonzero principal ideal `h D`, and `h` lies in at most
countably many maximal ideals. -/
theorem hasSmithNormalForm_of_hasCountableCharacter (hcc : HasCountableCharacter D)
    (F : Matrix (Fin 2) (Fin 2) D) : HasSmithNormalForm F := by
  classical
  -- the ideal generated by the entries is principal, `c = g D`
  set c : Ideal D := Ideal.span (Set.range fun p : Fin 2 × Fin 2 => F p.1 p.2)
  obtain ⟨g, hg⟩ := (IsBezout.isPrincipal_of_FG c
    ⟨(Finset.univ.image fun p : Fin 2 × Fin 2 => F p.1 p.2), by simp [c]⟩).principal
  have hmemc : ∀ i j, F i j ∈ c := fun i j => Ideal.subset_span ⟨(i, j), rfl⟩
  by_cases hg0 : g = 0
  · -- `F = 0`
    have hF0 : F = 0 := by
      ext i j
      have := hmemc i j
      rw [hg, hg0, Submodule.span_singleton_eq_bot.2 rfl, Submodule.mem_bot] at this
      exact this
    refine ⟨F, MatrixEquivalent.refl F, (isSmithNormalForm_iff_chain F).2
      ⟨0, fun i j => ?_, fun k _ => dvd_refl _⟩⟩
    simp [hF0]
  -- divide out `g`: `F = g F₁` with the entries of `F₁` generating `D`
  have hdiv : ∀ i j, ∃ z : D, F i j = g * z := fun i j => by
    have := hmemc i j
    rw [hg] at this
    obtain ⟨z, hz⟩ := Submodule.mem_span_singleton.1 this
    exact ⟨z, by rw [← hz, smul_eq_mul, mul_comm]⟩
  choose F₁ hF₁ using hdiv
  have hFg : F = g • Matrix.of F₁ := by ext i j; rw [hF₁]; rfl
  have hU : EntriesGenerate (Matrix.of F₁) := by
    intro I hI
    have hle : c ≤ I * Ideal.span {g} := by
      rw [Ideal.span_le]
      rintro _ ⟨⟨i, j⟩, rfl⟩
      show F i j ∈ I * Ideal.span {g}
      rw [hF₁, mul_comm g]
      exact Ideal.mul_mem_mul (hI i j) (Ideal.mem_span_singleton_self g)
    have hgc : g ∈ c := by rw [hg]; exact Submodule.mem_span_singleton_self g
    obtain ⟨z, hz, hzg⟩ := Ideal.mem_mul_span_singleton.1 (hle hgc)
    have hz1 : z = 1 := mul_right_cancel₀ hg0 (by rw [hzg, one_mul])
    rw [hz1] at hz
    exact (Ideal.eq_top_iff_one I).2 hz
  rw [hFg]
  refine HasSmithNormalForm.smul ?_ g
  -- a unimodular matrix whose first row is nonzero has a Smith normal form
  have key : ∀ N : Matrix (Fin 2) (Fin 2) D, EntriesGenerate N → (N 0 0 ≠ 0 ∨ N 0 1 ≠ 0) →
      HasSmithNormalForm N := by
    intro N hN hrow
    apply hasSmithNormalForm_of_countable_firstRow N hN
    obtain ⟨h, hh⟩ := (IsBezout.isPrincipal_of_FG (Ideal.span {N 0 0, N 0 1})
      (Submodule.fg_span ((Set.finite_singleton _).insert _))).principal
    have hh0 : h ≠ 0 := by
      rintro rfl
      have h0 : N 0 0 ∈ Ideal.span {N 0 0, N 0 1} := Ideal.subset_span (by simp)
      have h1 : N 0 1 ∈ Ideal.span {N 0 0, N 0 1} := Ideal.subset_span (by simp)
      rw [hh, Submodule.span_singleton_eq_bot.2 rfl, Submodule.mem_bot] at h0 h1
      rcases hrow with h | h <;> contradiction
    refine (hcc h (mem_nonZeroDivisors_of_ne_zero hh0)).mono ?_
    rintro 𝔪 ⟨h𝔪, hh𝔪⟩
    refine ⟨h𝔪, ?_⟩
    rw [hh] at hh𝔪
    exact (Submodule.span_singleton_le_iff_mem _ _).1 hh𝔪
  by_cases hrow : (Matrix.of F₁) 0 0 ≠ 0 ∨ (Matrix.of F₁) 0 1 ≠ 0
  · exact key _ hU hrow
  · -- the first row vanishes: interchange the rows
    push Not at hrow
    refine HasSmithNormalForm.of_equiv (MatrixEquivalent.mul_left (glSwap D)) (key _
      (hU.equiv (MatrixEquivalent.mul_left _)) ?_)
    by_contra hcon
    push Not at hcon
    apply (zero_ne_one : (0 : D) ≠ 1)
    have htop := hU ⊥ (fun i j => by
      fin_cases i <;> fin_cases j
      · exact hrow.1 ▸ Ideal.zero_mem _
      · exact hrow.2 ▸ Ideal.zero_mem _
      · have := hcon.1
        simp [glSwap, Matrix.mul_apply, Fin.sum_univ_two] at this
        simp [this]
      · have := hcon.2
        simp [glSwap, Matrix.mul_apply, Fin.sum_univ_two] at this
        simp [this])
    have h1 : (1 : D) ∈ (⊥ : Ideal D) := htop ▸ Submodule.mem_top
    exact ((Ideal.mem_bot.1 h1)).symm

end Iteration

/-! ## Corollary 6.4 and the maximal ideals containing `(1 ± x, y)` -/

/-- The entries of `M` generate `R`, by (2.1). -/
theorem entriesGenerate_M : EntriesGenerate (M.map R.ι) := by
  intro I hI
  rw [eq_top_iff, ← span_entries_M_map, Ideal.span_le]
  rintro z (rfl | rfl | rfl)
  · simpa [M] using hI 0 0
  · simpa [M] using hI 0 1
  · simpa [M] using hI 1 1

/-- **Corollary 6.4** (`cor:not-countable-character`). The ring `R` does not have countable
character. In particular, some nonzero element of the countable ring `R` belongs to uncountably
many maximal ideals.

Proof: if `R` had countable character, Couchot's theorem (here in the special case of `2 × 2`
matrices, `hasSmithNormalForm_of_hasCountableCharacter`) would give a Smith normal form of `M`,
contrary to Theorem 1.1. -/
theorem not_hasCountableCharacter :
    ¬ HasCountableCharacter R ∧
      ∃ a : R, a ≠ 0 ∧ ¬ {𝔪 : Ideal R | 𝔪.IsMaximal ∧ a ∈ 𝔪}.Countable := by
  have h1 : ¬ HasCountableCharacter R := fun h =>
    not_hasSmithNormalForm (hasSmithNormalForm_of_hasCountableCharacter h _)
  refine ⟨h1, ?_⟩
  rw [hasCountableCharacter_iff] at h1
  push Not at h1
  exact h1

/-- **Uncountably many maximal ideals of `R` contain `(1 + x, y)`, and uncountably many contain
`(1 - x, y)`.** Apply the `2 × 2` consequence of [CS, Lemma 5.1] to `M`, and to the matrix
obtained from `M` by interchanging both its rows and its columns (which is equivalent to `M`);
their first rows are `(1 + x, y)` and `(1 - x, y)`. -/
theorem uncountable_maximal_ideals :
    ¬ {𝔪 : Ideal R | 𝔪.IsMaximal ∧ Ideal.span {R.ι (1 + x), R.ι y} ≤ 𝔪}.Countable ∧
      ¬ {𝔪 : Ideal R | 𝔪.IsMaximal ∧ Ideal.span {R.ι (1 - x), R.ι y} ≤ 𝔪}.Countable := by
  refine ⟨fun hc => not_hasSmithNormalForm ?_, fun hc => not_hasSmithNormalForm ?_⟩
  · refine hasSmithNormalForm_of_countable_firstRow _ entriesGenerate_M ?_
    simpa [M] using hc
  · -- interchange both the rows and the columns of `M`
    set S := ((glSwap R : GL (Fin 2) R) : Matrix (Fin 2) (Fin 2) R)
    have hEq : MatrixEquivalent (M.map R.ι) (S * M.map R.ι * S) := ⟨glSwap R, glSwap R, rfl⟩
    refine HasSmithNormalForm.of_equiv hEq
      (hasSmithNormalForm_of_countable_firstRow _ (entriesGenerate_M.equiv hEq) ?_)
    simpa [S, M, glSwap, Matrix.mul_apply, Matrix.vecMul, dotProduct, Fin.sum_univ_two] using hc

/-! ## The countable domain `C = ℚ[t, z₁, z₂, …]` -/

section ExampleC

open MvPolynomial

/-- The countable domain `C = ℚ[t, z₁, z₂, …]`, with `t = X 0` and `z_{k+1} = X (k + 1)`. -/
abbrev ExampleC : Type := MvPolynomial ℕ ℚ

/-- `0 ↦ 0`, `1 ↦ 1`, on `ε_k ∈ {0, 1}` (encoded as `Bool`). -/
def boolToRat (b : Bool) : ℚ := if b then 1 else 0

lemma boolToRat_injective : Function.Injective boolToRat := by
  intro a b h
  cases a <;> cases b <;> simp_all [boolToRat]

/-- The point `(t, z₁, z₂, …) = (0, ε₁, ε₂, …)`, for `ε : ℕ → Bool` (with `ε k` standing for
`ε_{k+1}`). -/
def pointε (ε : ℕ → Bool) : ℕ → ℚ := fun k => if k = 0 then 0 else boolToRat (ε (k - 1))

/-- Evaluation at the point `(0, ε₁, ε₂, …)`. -/
def evalε (ε : ℕ → Bool) : ExampleC →ₐ[ℚ] ℚ := MvPolynomial.aeval (pointε ε)

/-- The ideal `𝔪_ε = (t, z₁ - ε₁, z₂ - ε₂, …)` of `C`. -/
def maxIdealε (ε : ℕ → Bool) : Ideal ExampleC :=
  Ideal.span (Set.range fun k : ℕ => (X k - C (pointε ε k) : ExampleC))

/-- Every polynomial is congruent to its value at a point `a` modulo `(X k - a_k)_k`. -/
lemma sub_C_eval_mem_span (a : ℕ → ℚ) (P : ExampleC) :
    P - C (MvPolynomial.eval a P) ∈
      Ideal.span (Set.range fun k : ℕ => (X k - C (a k) : ExampleC)) := by
  induction P using MvPolynomial.induction_on with
  | C q => simp
  | add P Q hP hQ =>
    have : P + Q - C (MvPolynomial.eval a (P + Q)) =
        (P - C (MvPolynomial.eval a P)) + (Q - C (MvPolynomial.eval a Q)) := by
      simp only [map_add]; ring
    rw [this]
    exact Ideal.add_mem _ hP hQ
  | mul_X P k hP =>
    have : P * X k - C (MvPolynomial.eval a (P * X k)) =
        (P - C (MvPolynomial.eval a P)) * X k + C (MvPolynomial.eval a P) * (X k - C (a k)) := by
      simp only [map_mul, eval_X]; ring
    rw [this]
    exact Ideal.add_mem _ (Ideal.mul_mem_right _ _ hP)
      (Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨k, rfl⟩))

/-- `𝔪_ε` is the kernel of the evaluation at `(0, ε₁, ε₂, …)`. -/
lemma maxIdealε_eq_ker (ε : ℕ → Bool) : maxIdealε ε = RingHom.ker (evalε ε) := by
  apply le_antisymm
  · rw [maxIdealε, Ideal.span_le]
    rintro _ ⟨k, rfl⟩
    simp [evalε, RingHom.mem_ker]
  · intro P hP
    have hP' : MvPolynomial.eval (pointε ε) P = 0 := by
      rw [RingHom.mem_ker] at hP
      simpa [evalε, MvPolynomial.aeval_eq_eval] using hP
    have := sub_C_eval_mem_span (pointε ε) P
    rwa [hP', map_zero, sub_zero] at this

/-- Each quotient `C/𝔪_ε` is `ℚ`. -/
def quotientMaxIdealε (ε : ℕ → Bool) : (ExampleC ⧸ maxIdealε ε) ≃ₐ[ℚ] ℚ :=
  (Ideal.quotientEquivAlgOfEq ℚ (maxIdealε_eq_ker ε)).trans
    (Ideal.quotientKerAlgEquivOfSurjective fun q => ⟨C q, by simp [evalε]⟩)

/-- Each `𝔪_ε` is a maximal ideal. -/
lemma maxIdealε_isMaximal (ε : ℕ → Bool) : (maxIdealε ε).IsMaximal := by
  rw [maxIdealε_eq_ker]
  exact RingHom.ker_isMaximal_of_surjective _ fun q => ⟨C q, by simp [evalε]⟩

/-- Every `𝔪_ε` contains `t`. -/
lemma t_mem_maxIdealε (ε : ℕ → Bool) : (X 0 : ExampleC) ∈ maxIdealε ε := by
  have h : (X 0 - C (pointε ε 0) : ExampleC) ∈ maxIdealε ε := Ideal.subset_span ⟨0, rfl⟩
  simpa [pointε] using h

/-- The ideals `𝔪_ε` are pairwise distinct. -/
lemma maxIdealε_injective : Function.Injective maxIdealε := by
  intro ε ε' h
  funext k
  have hmem : (X (k + 1) - C (boolToRat (ε k)) : ExampleC) ∈ maxIdealε ε := by
    have h1 : (X (k + 1) - C (pointε ε (k + 1)) : ExampleC) ∈ maxIdealε ε :=
      Ideal.subset_span ⟨k + 1, rfl⟩
    have h2 : pointε ε (k + 1) = boolToRat (ε k) := by simp [pointε]
    rwa [h2] at h1
  rw [h, maxIdealε_eq_ker, RingHom.mem_ker] at hmem
  simp only [evalε, map_sub, MvPolynomial.aeval_X, MvPolynomial.aeval_C, pointε,
    Nat.add_one_ne_zero, ite_false, Nat.add_sub_cancel] at hmem
  have : boolToRat (ε' k) = boolToRat (ε k) := by
    have := sub_eq_zero.1 hmem
    simpa using this
  exact (boolToRat_injective this).symm

lemma not_countable_nat_bool : ¬ Countable (ℕ → Bool) := by
  intro h
  obtain ⟨f, hf⟩ := exists_surjective_nat (ℕ → Bool)
  apply Function.cantor_surjective (fun n => {k | f n k = true})
  intro s
  classical
  obtain ⟨n, hn⟩ := hf (fun k => decide (k ∈ s))
  exact ⟨n, by ext k; simp [hn]⟩

/-- `C` is countable. -/
theorem exampleC_countable : Countable ExampleC := inferInstance

/-- **The example `C = ℚ[t, z₁, z₂, …]`**: countability of the underlying set does not imply
countable character. The countable domain `C` has uncountably many distinct maximal ideals
`𝔪_ε = (t, z₁ - ε₁, z₂ - ε₂, …)`, each with quotient `ℚ` (`quotientMaxIdealε`), and all of them
contain the nonzero element `t`. -/
theorem exampleC_uncountable :
    (X 0 : ExampleC) ≠ 0 ∧
      ¬ {𝔪 : Ideal ExampleC | 𝔪.IsMaximal ∧ (X 0 : ExampleC) ∈ 𝔪}.Countable := by
  refine ⟨MvPolynomial.X_ne_zero 0, fun hc => not_countable_nat_bool ?_⟩
  have hsub : Set.range maxIdealε ⊆
      {𝔪 : Ideal ExampleC | 𝔪.IsMaximal ∧ (X 0 : ExampleC) ∈ 𝔪} := by
    rintro _ ⟨ε, rfl⟩
    exact ⟨maxIdealε_isMaximal ε, t_mem_maxIdealε ε⟩
  have := (hc.mono hsub).to_subtype
  exact Function.Injective.countable (f := fun ε => (⟨maxIdealε ε, ε, rfl⟩ : Set.range maxIdealε))
    fun a b hab => maxIdealε_injective (congrArg Subtype.val hab)

/-- `C` does not have countable character. -/
theorem exampleC_not_hasCountableCharacter : ¬ HasCountableCharacter ExampleC := by
  rw [hasCountableCharacter_iff]
  intro h
  exact exampleC_uncountable.2 (h _ exampleC_uncountable.1)

end ExampleC

end BezoutCounterexample
