import BezoutCounterexample.Basic

/-!
# Proposition 6.5: a general countable reduction

This file formalizes **Proposition 6.5** (`prop:countable-reduction`) of the paper: if `D` is a
Bézout domain and `F` is a finite matrix over `D` with no Smith normal form, then there is a
countable Bézout subdomain `S ⊆ D` that contains every entry of `F` and over which `F` still has no
Smith normal form (`countable_reduction`).

The proof follows the paper: `S₀` is the subring generated by `1` and the entries of `F`; given a
countable subring `Sₙ`, for every pair `a, b ∈ Sₙ` we choose `g, r, s, c, d ∈ D` with
`g = r a + s b`, `a = g c`, `b = g d` (all zero when `(a, b) = (0, 0)`; `bezoutWitness`), and
`Sₙ₊₁` is the subring generated by `Sₙ` and all chosen witnesses (`reductionChain`). Then
`S = ⋃ Sₙ` is a countable Bézout domain, and an equivalence of `F` to Smith normal form over `S`
would remain one over `D` (`HasSmithNormalForm.map`).
-/

noncomputable section

namespace BezoutCounterexample

open Set

/-! ## Smith normal forms along ring homomorphisms -/

section Map

variable {A S : Type*} [CommRing A] [CommRing S]

/-- A diagonal matrix with divisibility chain remains one under a ring homomorphism (for the
Smith normal form this uses the chain form `isSmithNormalForm_iff_chain`). -/
theorem IsSmithNormalForm.map {m n : ℕ} {G : Matrix (Fin m) (Fin n) A}
    (h : IsSmithNormalForm G) (f : A →+* S) : IsSmithNormalForm (G.map f) := by
  rw [isSmithNormalForm_iff_chain] at h ⊢
  obtain ⟨d, hd, hdiv⟩ := h
  refine ⟨fun k => f (d k), fun i j => ?_, fun k hk => map_dvd f (hdiv k hk)⟩
  rw [Matrix.map_apply, hd]
  split_ifs <;> simp

/-- An equivalence to Smith normal form remains one under a ring homomorphism, since matrix
inverses and divisibility identities are preserved. -/
theorem HasSmithNormalForm.map {m n : ℕ} {F : Matrix (Fin m) (Fin n) A}
    (h : HasSmithNormalForm F) (f : A →+* S) : HasSmithNormalForm (F.map f) := by
  obtain ⟨G, ⟨P, Q, hPQ⟩, hG⟩ := h
  refine ⟨G.map f, ⟨Matrix.GeneralLinearGroup.map f P, Matrix.GeneralLinearGroup.map f Q, ?_⟩,
    hG.map f⟩
  rw [← hPQ, Matrix.map_mul, Matrix.map_mul]
  rfl

end Map

/-! ## Proposition 6.5 -/

section CountableReduction

variable {D : Type*} [CommRing D]

lemma countable_closure {s : Set D} (hs : s.Countable) :
    (Subring.closure s : Set D).Countable := by
  have h1 : (Subring.closure s : Set D) = (Algebra.adjoin ℤ s : Set D) := by
    rw [Algebra.adjoin_int]; rfl
  rw [h1, Algebra.adjoin_eq_range]
  have := hs.to_subtype
  exact Set.countable_range _

/-- In a Bézout domain every pair `(a, b)` has witnesses `w = (g, r, s, c, d)` with
`g = r a + s b`, `a = g c` and `b = g d`. -/
lemma exists_bezout_witness [IsBezout D] (a b : D) :
    ∃ w : Fin 5 → D, w 0 = w 1 * a + w 2 * b ∧ a = w 0 * w 3 ∧ b = w 0 * w 4 := by
  obtain ⟨g, hg⟩ := (IsBezout.iff_span_pair_isPrincipal.1 inferInstance a b).principal
  have hgmem : g ∈ Ideal.span {a, b} := by rw [hg]; exact Submodule.mem_span_singleton_self g
  obtain ⟨r, s, hrs⟩ := Ideal.mem_span_pair.1 hgmem
  have ha : a ∈ Ideal.span {a, b} := Ideal.subset_span (by simp)
  have hb : b ∈ Ideal.span {a, b} := Ideal.subset_span (by simp)
  rw [hg] at ha hb
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.1 ha
  obtain ⟨d, hd⟩ := Submodule.mem_span_singleton.1 hb
  refine ⟨![g, r, s, c, d], ?_, ?_, ?_⟩
  · simp [hrs]
  · simp only [Matrix.cons_val_zero, Matrix.cons_val_three]
    rw [← hc, smul_eq_mul, mul_comm]; rfl
  · simp only [Matrix.cons_val_zero, Matrix.cons_val_four]
    rw [← hd, smul_eq_mul, mul_comm]; rfl

variable [IsBezout D]

open Classical in
/-- The chosen witnesses `(g, r, s, c, d)` for a pair `(a, b)`; for `(a, b) = (0, 0)` all five
elements are zero. -/
def bezoutWitness (p : D × D) : Fin 5 → D :=
  if p = (0, 0) then 0 else Classical.choose (exists_bezout_witness p.1 p.2)

lemma bezoutWitness_spec (a b : D) :
    bezoutWitness (a, b) 0 = bezoutWitness (a, b) 1 * a + bezoutWitness (a, b) 2 * b ∧
      a = bezoutWitness (a, b) 0 * bezoutWitness (a, b) 3 ∧
      b = bezoutWitness (a, b) 0 * bezoutWitness (a, b) 4 := by
  by_cases h : (a, b) = (0, 0)
  · obtain ⟨rfl, rfl⟩ := Prod.mk.inj h
    simp [bezoutWitness]
  · rw [bezoutWitness, ite_eq_right h]
    exact Classical.choose_spec (exists_bezout_witness a b)

/-- The chain of countable subrings `S₀ ⊆ S₁ ⊆ ⋯` of the proof of Proposition 6.5: `S₀` is
generated by `s₀`, and `Sₙ₊₁` is generated by `Sₙ` and the witnesses of all pairs of elements of
`Sₙ`. -/
def reductionChain (s₀ : Set D) : ℕ → Subring D
  | 0 => Subring.closure s₀
  | k + 1 => Subring.closure ((reductionChain s₀ k : Set D) ∪
      ⋃ p ∈ (reductionChain s₀ k : Set D) ×ˢ (reductionChain s₀ k : Set D),
        Set.range (bezoutWitness p))

lemma reductionChain_le_succ (s₀ : Set D) (k : ℕ) :
    reductionChain s₀ k ≤ reductionChain s₀ (k + 1) := fun _ hz =>
  Subring.subset_closure (Or.inl hz)

lemma reductionChain_mono (s₀ : Set D) : Monotone (reductionChain s₀) :=
  monotone_nat_of_le_succ (reductionChain_le_succ s₀)

lemma reductionChain_countable {s₀ : Set D} (hs : s₀.Countable) (k : ℕ) :
    (reductionChain s₀ k : Set D).Countable := by
  induction k with
  | zero => exact countable_closure hs
  | succ k ih =>
    apply countable_closure
    refine ih.union ?_
    exact (ih.prod ih).biUnion fun p _ => Set.countable_range _

lemma bezoutWitness_mem (s₀ : Set D) {k : ℕ} {a b : D} (ha : a ∈ reductionChain s₀ k)
    (hb : b ∈ reductionChain s₀ k) (i : Fin 5) :
    bezoutWitness (a, b) i ∈ reductionChain s₀ (k + 1) := by
  apply Subring.subset_closure
  exact Or.inr (Set.mem_biUnion (x := (a, b)) ⟨ha, hb⟩ ⟨i, rfl⟩)

/-- **Proposition 6.5** (`prop:countable-reduction`). Let `D` be a Bézout domain, and let `F` be a
finite matrix over `D` with no Smith normal form. There is a countable Bézout subdomain `S ⊆ D`
that contains every entry of `F` and over which `F` still has no Smith normal form (`F` viewed
over `S` is the matrix `F'` with `F'.map S.subtype = F`). -/
theorem countable_reduction [IsDomain D] {m n : ℕ} (F : Matrix (Fin m) (Fin n) D)
    (hF : ¬ HasSmithNormalForm F) :
    ∃ S : Subring D, Countable S ∧ IsDomain S ∧ IsBezout S ∧ (∀ i j, F i j ∈ S) ∧
      ∃ F' : Matrix (Fin m) (Fin n) S, F'.map S.subtype = F ∧ ¬ HasSmithNormalForm F' := by
  -- `S₀` is the subring generated by `1` and the entries of `F`
  set s₀ : Set D := Set.range fun ij : Fin m × Fin n => F ij.1 ij.2
  have hs₀ : s₀.Countable := Set.countable_range _
  set S : Subring D := ⨆ k, reductionChain s₀ k
  have hdir : Directed (· ≤ ·) (reductionChain s₀) := (reductionChain_mono s₀).directed_le
  have hmem : ∀ z, z ∈ S ↔ ∃ k, z ∈ reductionChain s₀ k := fun z =>
    Subring.mem_iSup_of_directed hdir
  have hle : ∀ k, reductionChain s₀ k ≤ S := fun k => le_iSup (reductionChain s₀) k
  have hF0 : ∀ i j, F i j ∈ S := fun i j => hle 0 (Subring.subset_closure ⟨(i, j), rfl⟩)
  refine ⟨S, ?_, inferInstance, ?_, hF0, ?_⟩
  · -- `S = ⋃ Sₙ` is countable
    have : (S : Set D) = ⋃ k, (reductionChain s₀ k : Set D) :=
      Subring.coe_iSup_of_directed hdir
    have hc : (S : Set D).Countable := by
      rw [this]; exact Set.countable_iUnion fun k => reductionChain_countable hs₀ k
    exact hc.to_subtype
  · -- `S` is Bézout: if `a, b ∈ Sₙ`, the chosen identities give `(a, b) S = g S`
    rw [IsBezout.iff_span_pair_isPrincipal]
    intro a b
    obtain ⟨k₁, hk₁⟩ := (hmem a).1 a.2
    obtain ⟨k₂, hk₂⟩ := (hmem b).1 b.2
    have ha : (a : D) ∈ reductionChain s₀ (max k₁ k₂) :=
      reductionChain_mono s₀ (le_max_left _ _) hk₁
    have hb : (b : D) ∈ reductionChain s₀ (max k₁ k₂) :=
      reductionChain_mono s₀ (le_max_right _ _) hk₂
    have hw : ∀ i, bezoutWitness ((a : D), (b : D)) i ∈ S := fun i =>
      hle _ (bezoutWitness_mem s₀ ha hb i)
    let w : Fin 5 → S := fun i => ⟨bezoutWitness ((a : D), (b : D)) i, hw i⟩
    obtain ⟨h0, h3, h4⟩ := bezoutWitness_spec (a : D) (b : D)
    have e0 : w 0 = w 1 * a + w 2 * b := Subtype.ext h0
    have e3 : a = w 0 * w 3 := Subtype.ext h3
    have e4 : b = w 0 * w 4 := Subtype.ext h4
    refine ⟨⟨w 0, le_antisymm ?_ ?_⟩⟩
    · rw [Ideal.span_le]
      rintro z (rfl | rfl)
      · rw [e3]; exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)
      · rw [e4]; exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)
    · show Ideal.span {w 0} ≤ Ideal.span {a, b}
      rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, e0]
      exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp)))
        (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp)))
  · -- a Smith normal form over `S` would remain one over `D`
    refine ⟨fun i j => ⟨F i j, hF0 i j⟩, ?_, fun h => hF ?_⟩
    · ext i j; rfl
    · have := h.map S.subtype
      convert this
      ext i j; rfl

end CountableReduction

end BezoutCounterexample
