import BezoutCounterexample.Factoriality

/-!
# Section 6.3: an explicit principalization extension (algebra)

This file formalizes the algebraic half of Section 6.3 of the paper; the real points are treated in
`ExplicitRealPoints.lean`.

The ideal `(x - 1, y)` of `ℚ[x, y]` admits a simple affine principalization. Writing
`t = T⁻¹`, `u = (x - 1) T`, `v = y T` identifies the extended Rees algebra with `ℚ[t, u, v]`, and
Jouanolou's construction applied to the generators `u`, `v` gives

  `A* = ℚ[t, u, v, r₀, r₁]/(r₀ u + r₁ v - 1)` (`Astar`, generated by `t u v r₀ r₁`),

together with `φ : ℚ[x, y] → A*`, `x ↦ 1 + t u`, `y ↦ t v`.

* `span_u_v`: `(u, v) = A*`; `map_span_eq`: `(x - 1, y) A* = t (u, v) A* = t A*`.
* `rel_prime`: viewed as a polynomial in `u` over the UFD `ℚ[t, v, r₀, r₁]`, `r₀ u + r₁ v - 1` is
  primitive and linear, hence irreducible by Gauss's lemma, hence prime; so `A*` is a domain.
* `equivAu`, `equivAv`: `A*[u⁻¹] ≅ ℚ[t, u, u⁻¹, v, r₁]` and `A*[v⁻¹] ≅ ℚ[t, v, v⁻¹, u, r₀]`
  (the second one is obtained from the first by the involution `u ↔ v`, `r₀ ↔ r₁` of `A*`). Both
  are smooth over `ℚ`, and `Spec A*` is covered by the open sets `u ≠ 0` and `v ≠ 0`, so `A*` is
  smooth over `ℚ` (`Astar_smooth`).
* `quotientEquiv`: `A*/(u) ≅ ℚ[t, v, v⁻¹, r₀]`, a domain, so `u` is a prime element of `A*`
  (`u_prime`).
* `A*[u⁻¹]` is a UFD, so `A*` is factorial by Nagata's criterion (`Astar_ufd`); `AstarSFD` is `A*`
  as a smooth finitely generated factorial `ℚ`-domain.
* `φ_injective`: `ℚ[x, y] → A*` is injective, since `t ↦ 1`, `u ↦ x - 1`, `v ↦ y`,
  `r₀ ↦ (x - 1)⁻¹`, `r₁ ↦ 0` defines a homomorphism `A* → ℚ(x, y)` whose composite with `φ` is the
  inclusion `ℚ[x, y] ⊆ ℚ(x, y)`.

The optional identification of the extended Rees algebra `ℚ[x, y, T⁻¹, (x - 1)T, yT]` with
`ℚ[t, u, v]` and the claims about the invariant of `(x - 1, y)` are not formalized.
-/

noncomputable section

namespace BezoutCounterexample.Explicit

open MvPolynomial

/-! ## The ring `A*` -/

/-- The polynomial ring `ℚ[t, u, v, r₀, r₁]`; the variables `t, u, v, r₀, r₁` are
`X 0, X 1, X 2, X 3, X 4`. -/
abbrev P : Type := MvPolynomial (Fin 5) ℚ

/-- The relation `r₀ u + r₁ v - 1 ∈ ℚ[t, u, v, r₀, r₁]`. -/
def rel : P := X 3 * X 1 + X 4 * X 2 - 1

/-- **`A* = ℚ[t, u, v, r₀, r₁]/(r₀ u + r₁ v - 1)`.** -/
abbrev Astar : Type := P ⧸ Ideal.span {rel}

/-- The quotient map `ℚ[t, u, v, r₀, r₁] → A*`. -/
abbrev mk : P →ₐ[ℚ] Astar := Ideal.Quotient.mkₐ ℚ _

/-- The generator `t` of `A*`. -/
def t : Astar := mk (X 0)
/-- The generator `u` of `A*`. -/
def u : Astar := mk (X 1)
/-- The generator `v` of `A*`. -/
def v : Astar := mk (X 2)
/-- The generator `r₀` of `A*`. -/
def r₀ : Astar := mk (X 3)
/-- The generator `r₁` of `A*`. -/
def r₁ : Astar := mk (X 4)

lemma mk_rel : mk rel = 0 := Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.subset_span rfl)

/-- The relation `r₀ u + r₁ v = 1` in `A*`. -/
theorem rel_eq_one : r₀ * u + r₁ * v = 1 := by
  have h := mk_rel
  simp only [rel, map_add, map_mul, map_sub, map_one] at h
  simp only [r₀, u, r₁, v]
  linear_combination h

/-- Homomorphisms out of `A*`: `(t, u, v, r₀, r₁) ↦ (a 0, …, a 4)`, for `a` with
`a₃ a₁ + a₄ a₂ = 1`. -/
def lift {S : Type*} [CommRing S] [Algebra ℚ S] (a : Fin 5 → S) (h : a 3 * a 1 + a 4 * a 2 = 1) :
    Astar →ₐ[ℚ] S :=
  Ideal.Quotient.liftₐ _ (MvPolynomial.aeval a) (by
    intro z hz
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.1 hz
    have h' : a 3 * a 1 + a 4 * a 2 - 1 = 0 := by rw [h, sub_self]
    simp [rel, h'])

section Lift

variable {S : Type*} [CommRing S] [Algebra ℚ S] (a : Fin 5 → S) (h : a 3 * a 1 + a 4 * a 2 = 1)

lemma lift_mk (F : P) : lift a h (mk F) = MvPolynomial.aeval a F := rfl

@[simp] lemma lift_t : lift a h t = a 0 := MvPolynomial.aeval_X a 0
@[simp] lemma lift_u : lift a h u = a 1 := MvPolynomial.aeval_X a 1
@[simp] lemma lift_v : lift a h v = a 2 := MvPolynomial.aeval_X a 2
@[simp] lemma lift_r₀ : lift a h r₀ = a 3 := MvPolynomial.aeval_X a 3
@[simp] lemma lift_r₁ : lift a h r₁ = a 4 := MvPolynomial.aeval_X a 4

end Lift

/-- Two homomorphisms out of `A*` agreeing on `t, u, v, r₀, r₁` are equal. -/
lemma algHom_ext {S : Type*} [CommRing S] [Algebra ℚ S] {f g : Astar →ₐ[ℚ] S}
    (ht : f t = g t) (hu : f u = g u) (hv : f v = g v) (hr₀ : f r₀ = g r₀)
    (hr₁ : f r₁ = g r₁) : f = g := by
  apply Ideal.Quotient.algHom_ext ℚ
  apply MvPolynomial.algHom_ext
  intro i
  fin_cases i
  · exact ht
  · exact hu
  · exact hv
  · exact hr₀
  · exact hr₁

/-- `A*` is generated by `t, u, v, r₀, r₁`. -/
theorem adjoin_gens : Algebra.adjoin ℚ (Set.range fun i : Fin 5 => mk (X i)) = ⊤ := by
  rw [Algebra.adjoin_range_eq_range_aeval, eq_top_iff]
  intro z _
  obtain ⟨F, rfl⟩ := Ideal.Quotient.mk_surjective z
  refine ⟨F, ?_⟩
  have h : (MvPolynomial.aeval fun i : Fin 5 => mk (X i)) = mk :=
    (MvPolynomial.aeval_unique mk).symm
  rw [h]
  rfl

/-! ## The homomorphism `φ : ℚ[x, y] → A*` and the ideal `(x - 1, y)` -/

/-- The homomorphism `φ : ℚ[x, y] → A*`, `x ↦ 1 + t u`, `y ↦ t v`. -/
def φ : A₀ →ₐ[ℚ] Astar := MvPolynomial.aeval ![1 + t * u, t * v]

@[simp] lemma φ_x : φ x = 1 + t * u := by simp [φ, x]
@[simp] lemma φ_y : φ y = t * v := by simp [φ, y]

/-- **`(u, v) = A*`**, by `r₀ u + r₁ v = 1`. -/
theorem span_u_v : (Ideal.span {u, v} : Ideal Astar) = ⊤ := by
  rw [Ideal.eq_top_iff_one, ← rel_eq_one]
  exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp)))
    (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp)))

/-- **`(x - 1, y) A* = t (u, v) A* = t A*`**; in particular `(x - 1, y)` becomes principal in
`A*`. -/
theorem map_span_eq : (Ideal.span {x - 1, y} : Ideal A₀).map φ = Ideal.span {t} := by
  rw [Ideal.map_span, Set.image_pair, map_sub, map_one, φ_x, φ_y,
    show (1 + t * u - 1 : Astar) = t * u by ring]
  have h : (Ideal.span {t * u, t * v} : Ideal Astar) = Ideal.span {t} * Ideal.span {u, v} := by
    rw [Ideal.span_mul_span, Set.singleton_mul, Set.image_pair]
  rw [h, span_u_v, Ideal.mul_top]

/-! ## `r₀ u + r₁ v - 1` is prime (Gauss's lemma) -/

/-- The UFD `ℚ[t, v, r₀, r₁]` (variables `X 0, X 1, X 2, X 3`). -/
abbrev D4 : Type := MvPolynomial (Fin 4) ℚ

/-- The identification `ℚ[t, u, v, r₀, r₁] ≅ D4[u]`, `D4 = ℚ[t, v, r₀, r₁]`, viewing polynomials
as polynomials in `u`. -/
def eU : P ≃ₐ[ℚ] Polynomial D4 := (renameEquiv ℚ (Equiv.swap 0 1)).trans (finSuccEquiv ℚ 4)

lemma eU_X_zero : eU (X 0) = Polynomial.C (X 0) := by
  simp only [eU, AlgEquiv.trans_apply, renameEquiv_apply, rename_X]
  exact finSuccEquiv_X_succ (j := 0)

lemma eU_X_one : eU (X 1) = Polynomial.X := by
  simp only [eU, AlgEquiv.trans_apply, renameEquiv_apply, rename_X]
  exact finSuccEquiv_X_zero

lemma eU_X_two : eU (X 2) = Polynomial.C (X 1) := by
  simp only [eU, AlgEquiv.trans_apply, renameEquiv_apply, rename_X]
  exact finSuccEquiv_X_succ (j := 1)

lemma eU_X_three : eU (X 3) = Polynomial.C (X 2) := by
  simp only [eU, AlgEquiv.trans_apply, renameEquiv_apply, rename_X]
  exact finSuccEquiv_X_succ (j := 2)

lemma eU_X_four : eU (X 4) = Polynomial.C (X 3) := by
  simp only [eU, AlgEquiv.trans_apply, renameEquiv_apply, rename_X]
  exact finSuccEquiv_X_succ (j := 3)

/-- The coefficient `r₀` of `u`. -/
def coeffU : D4 := X 2

/-- The constant coefficient `r₁ v - 1`. -/
def coeff0 : D4 := X 3 * X 1 - 1

/-- `r₀ u + r₁ v - 1 = r₀ · u + (r₁ v - 1)`, a linear polynomial in `u` over `ℚ[t, v, r₀, r₁]`. -/
def relU : Polynomial D4 := Polynomial.C coeffU * Polynomial.X + Polynomial.C coeff0

lemma eU_rel : eU rel = relU := by
  simp only [rel, map_add, map_mul, map_sub, map_one, eU_X_one, eU_X_two, eU_X_three, eU_X_four,
    relU, coeffU, coeff0]
  ring

lemma coeffU_not_dvd_coeff0 : ¬ coeffU ∣ coeff0 := by
  rintro ⟨c, hc⟩
  have := congrArg (MvPolynomial.eval (fun _ => (0 : ℚ))) hc
  simp [coeffU, coeff0] at this

/-- `r₀ u + (r₁ v - 1)` is primitive. -/
lemma relU_isPrimitive : relU.IsPrimitive := by
  intro c hc
  rw [Polynomial.C_dvd_iff_dvd_coeff] at hc
  have h1 : c ∣ coeffU := by simpa [relU] using hc 1
  have h0 : c ∣ coeff0 := by simpa [relU] using hc 0
  obtain ⟨k, hk⟩ := h1
  rcases (MvPolynomial.X_prime.irreducible : Irreducible (X 2 : D4)).isUnit_or_isUnit hk with
    hc' | hk'
  · exact hc'
  · exfalso
    apply coeffU_not_dvd_coeff0
    obtain ⟨m, hm⟩ := h0
    obtain ⟨w, rfl⟩ := hk'
    refine ⟨((w⁻¹ : D4ˣ) : D4) * m, ?_⟩
    have : c = coeffU * ((w⁻¹ : D4ˣ) : D4) := by
      rw [hk, mul_assoc, Units.mul_inv, mul_one]
    rw [hm, this]; ring

/-- **Gauss's lemma**: the primitive linear polynomial `r₀ u + (r₁ v - 1)` is irreducible. -/
theorem relU_irreducible : Irreducible relU := by
  rw [relU_isPrimitive.irreducible_iff_irreducible_map_fraction_map (K := FractionRing D4)]
  apply Polynomial.irreducible_of_degree_eq_one
  have hr : algebraMap D4 (FractionRing D4) coeffU ≠ 0 := by
    intro h
    exact MvPolynomial.X_ne_zero 2
      ((IsFractionRing.injective D4 (FractionRing D4)) (by rw [coeffU] at h; rw [h, map_zero]))
  simp only [relU, Polynomial.map_add, Polynomial.map_mul, Polynomial.map_C, Polynomial.map_X]
  exact Polynomial.degree_linear hr

/-- **`r₀ u + r₁ v - 1` is prime.** -/
theorem rel_prime : Prime rel := by
  rw [← MulEquiv.prime_iff eU, eU_rel]
  exact UniqueFactorizationMonoid.irreducible_iff_prime.1 relU_irreducible

instance : (Ideal.span {rel}).IsPrime := (Ideal.span_singleton_prime rel_prime.ne_zero).2 rel_prime

/-- **`A*` is a domain.** -/
instance Astar_isDomain : IsDomain Astar := Ideal.Quotient.isDomain _

/-! ## `A*/(u) ≅ ℚ[t, v, v⁻¹, r₀]`, so `u` is prime -/

/-- `ℚ[t, v, r₀]` (variables `X 0, X 1, X 2`). -/
abbrev Q3 : Type := MvPolynomial (Fin 3) ℚ

/-- `ℚ[t, v, v⁻¹, r₀] = ℚ[t, v, r₀][1/v]`. -/
abbrev Bv : Type := Localization.Away (X 1 : Q3)

/-- `ℚ[t, v, v⁻¹, r₀]` is a domain. -/
instance Bv_isDomain : IsDomain Bv :=
  IsLocalization.isDomain_of_le_nonZeroDivisors Bv
    (powers_le_nonZeroDivisors_of_noZeroDivisors (show (X 1 : Q3) ≠ 0 from X_ne_zero 1))

/-- `v⁻¹ ∈ ℚ[t, v, v⁻¹, r₀]`. -/
def invBv : Bv := IsLocalization.Away.invSelf (X 1 : Q3)

lemma mul_invBv : algebraMap Q3 Bv (X 1) * invBv = 1 := IsLocalization.Away.mul_invSelf _

/-- `A* → ℚ[t, v, v⁻¹, r₀]`: `u ↦ 0`, `r₁ ↦ v⁻¹`. -/
def ψ₀ : Astar →ₐ[ℚ] Bv :=
  lift ![algebraMap Q3 Bv (X 0), 0, algebraMap Q3 Bv (X 1), algebraMap Q3 Bv (X 2), invBv] (by
    simp only [Matrix.cons_val, mul_zero, zero_add]
    rw [mul_comm]
    exact mul_invBv)

/-- The quotient map `A* → A*/(u)`. -/
abbrev qu : Astar →ₐ[ℚ] Astar ⧸ Ideal.span {u} := Ideal.Quotient.mkₐ ℚ _

/-- `A*/(u) → ℚ[t, v, v⁻¹, r₀]`. -/
def ψ : Astar ⧸ Ideal.span {u} →ₐ[ℚ] Bv :=
  Ideal.Quotient.liftₐ _ ψ₀ (by
    intro z hz
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.1 hz
    simp [ψ₀])

lemma ψ_qu (z : Astar) : ψ (qu z) = ψ₀ z := rfl

lemma qu_u : qu u = 0 := Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.subset_span rfl)

/-- In `A*/(u)`, `r₁ v = 1 - r₀ u = 1`. -/
lemma qu_r₁_mul_v : qu r₁ * qu v = 1 := by
  have h := congrArg qu rel_eq_one
  rw [map_add, map_mul, map_mul, map_one, qu_u] at h
  linear_combination h

/-- `v` is a unit of `A*/(u)`. -/
lemma qu_v_mul_r₁ : qu v * qu r₁ = 1 := by
  have h := congrArg qu rel_eq_one
  rw [map_add, map_mul, map_mul, map_one, qu_u] at h
  linear_combination h

lemma isUnit_qu_v : IsUnit (qu v) := ⟨⟨qu v, qu r₁, qu_v_mul_r₁, qu_r₁_mul_v⟩, rfl⟩

/-- `ℚ[t, v, r₀] → A*/(u)`. -/
def χ₀ : Q3 →ₐ[ℚ] Astar ⧸ Ideal.span {u} := MvPolynomial.aeval ![qu t, qu v, qu r₀]

lemma χ₀_X_zero : χ₀ (X 0) = qu t := MvPolynomial.aeval_X _ 0
lemma χ₀_X_one : χ₀ (X 1) = qu v := MvPolynomial.aeval_X _ 1
lemma χ₀_X_two : χ₀ (X 2) = qu r₀ := MvPolynomial.aeval_X _ 2

lemma isUnit_χ₀ : IsUnit (χ₀ (X 1)) := by
  rw [χ₀_X_one]
  exact isUnit_qu_v

/-- `ℚ[t, v, v⁻¹, r₀] → A*/(u)`. -/
def χ : Bv →ₐ[ℚ] Astar ⧸ Ideal.span {u} :=
  IsLocalization.Away.liftAlgHom (S := Bv) (P := Astar ⧸ Ideal.span {u}) (X 1 : Q3) isUnit_χ₀

lemma χ_algebraMap (F : Q3) : χ (algebraMap Q3 Bv F) = χ₀ F := by
  simp [χ]

lemma χ_ψ : χ.comp ψ = AlgHom.id ℚ _ := by
  apply Ideal.Quotient.algHom_ext ℚ
  apply Ideal.Quotient.algHom_ext ℚ
  apply MvPolynomial.algHom_ext
  intro i
  change χ (ψ (qu (mk (X i)))) = qu (mk (X i))
  rw [ψ_qu]
  fin_cases i
  · change χ (ψ₀ t) = qu t
    rw [ψ₀, lift_t]
    exact (χ_algebraMap _).trans χ₀_X_zero
  · change χ (ψ₀ u) = qu u
    rw [ψ₀, lift_u, qu_u]
    exact map_zero χ
  · change χ (ψ₀ v) = qu v
    rw [ψ₀, lift_v]
    exact (χ_algebraMap _).trans χ₀_X_one
  · change χ (ψ₀ r₀) = qu r₀
    rw [ψ₀, lift_r₀]
    exact (χ_algebraMap _).trans χ₀_X_two
  · change χ (ψ₀ r₁) = qu r₁
    rw [ψ₀, lift_r₁]
    -- `χ(v⁻¹)` is the inverse of `χ(v) = v`, which is `r₁` in `A*/(u)`
    have h1 : qu v * χ invBv = 1 := by
      have := congrArg χ mul_invBv
      rwa [map_mul, map_one, χ_algebraMap, χ₀_X_one] at this
    change χ invBv = qu r₁
    linear_combination qu r₁ * h1 - χ invBv * qu_r₁_mul_v

lemma ψ_χ : ψ.comp χ = AlgHom.id ℚ Bv := by
  apply IsLocalization.algHom_ext (Submonoid.powers (X 1 : Q3))
  apply MvPolynomial.algHom_ext
  intro i
  change ψ (χ (algebraMap Q3 Bv (X i))) = algebraMap Q3 Bv (X i)
  rw [χ_algebraMap]
  fin_cases i
  · change ψ (χ₀ (X 0)) = algebraMap Q3 Bv (X 0)
    rw [χ₀_X_zero, ψ_qu, ψ₀, lift_t]
    rfl
  · change ψ (χ₀ (X 1)) = algebraMap Q3 Bv (X 1)
    rw [χ₀_X_one, ψ_qu, ψ₀, lift_v]
    rfl
  · change ψ (χ₀ (X 2)) = algebraMap Q3 Bv (X 2)
    rw [χ₀_X_two, ψ_qu, ψ₀, lift_r₀]
    rfl

/-- **`A*/(u) ≅ ℚ[t, v, v⁻¹, r₀]`.** -/
def quotientEquiv : (Astar ⧸ Ideal.span {u}) ≃ₐ[ℚ] Bv := AlgEquiv.ofAlgHom ψ χ ψ_χ χ_ψ

/-- **`A*/(u)` is a domain.** -/
instance quotient_u_isDomain : IsDomain (Astar ⧸ Ideal.span {u}) :=
  Function.Injective.isDomain (ψ : Astar ⧸ Ideal.span {u} →+* Bv) quotientEquiv.injective

lemma u_ne_zero : u ≠ 0 := by
  intro h
  have := congrArg (lift (S := ℚ) ![0, 1, 0, 1, 0] (by norm_num)) h
  simp at this

/-- **`u` is a prime element of `A*`**, since `A*/(u)` is a domain. -/
theorem u_prime : Prime u := by
  rw [← Ideal.span_singleton_prime u_ne_zero, ← Ideal.Quotient.isDomain_iff_prime]
  infer_instance

/-! ## `A*[u⁻¹] ≅ ℚ[t, u, u⁻¹, v, r₁]` and `A*[v⁻¹] ≅ ℚ[t, v, v⁻¹, u, r₀]` -/

/-- `ℚ[t, u, v, r₁]` (variables `X 0, X 1, X 2, X 3`). -/
abbrev Q4 : Type := MvPolynomial (Fin 4) ℚ

/-- `L = ℚ[t, u, u⁻¹, v, r₁] = ℚ[t, u, v, r₁][1/u]`. -/
abbrev L : Type := Localization.Away (X 1 : Q4)

/-- `A*[u⁻¹]`. -/
abbrev Au : Type := Localization.Away u

/-- `A*[v⁻¹]`. -/
abbrev Av : Type := Localization.Away v

/-- `u⁻¹ ∈ L`. -/
def invL : L := IsLocalization.Away.invSelf (X 1 : Q4)

lemma mul_invL : algebraMap Q4 L (X 1) * invL = 1 := IsLocalization.Away.mul_invSelf _

/-- `A* → L`: `r₀ ↦ (1 - r₁ v) u⁻¹`. -/
def αA : Astar →ₐ[ℚ] L :=
  lift ![algebraMap Q4 L (X 0), algebraMap Q4 L (X 1), algebraMap Q4 L (X 2),
    (1 - algebraMap Q4 L (X 3) * algebraMap Q4 L (X 2)) * invL, algebraMap Q4 L (X 3)] (by
    simp only [Matrix.cons_val]
    linear_combination (1 - algebraMap Q4 L (X 3) * algebraMap Q4 L (X 2)) * mul_invL)

lemma αA_u : αA u = algebraMap Q4 L (X 1) := by rw [αA, lift_u]; rfl

lemma isUnit_αA_u : IsUnit (αA u) := by
  rw [αA_u]
  exact IsLocalization.Away.algebraMap_isUnit (X 1 : Q4)

/-- `A*[u⁻¹] → L`. -/
def α : Au →ₐ[ℚ] L := IsLocalization.Away.liftAlgHom u isUnit_αA_u

lemma α_algebraMap (z : Astar) : α (algebraMap Astar Au z) = αA z := by
  simp [α]

lemma isUnit_Au_u : IsUnit (algebraMap Astar Au u) := IsLocalization.Away.algebraMap_isUnit _

/-- `ℚ[t, u, v, r₁] → A*[u⁻¹]`. -/
def β₀ : Q4 →ₐ[ℚ] Au :=
  MvPolynomial.aeval ![algebraMap Astar Au t, algebraMap Astar Au u, algebraMap Astar Au v,
    algebraMap Astar Au r₁]

lemma β₀_X (i : Fin 4) : β₀ (X i) =
    ![algebraMap Astar Au t, algebraMap Astar Au u, algebraMap Astar Au v,
      algebraMap Astar Au r₁] i := MvPolynomial.aeval_X _ i

lemma isUnit_β₀ : IsUnit (β₀ (X 1)) := by
  rw [β₀_X]
  exact isUnit_Au_u

/-- `L → A*[u⁻¹]`. -/
def β : L →ₐ[ℚ] Au := IsLocalization.Away.liftAlgHom (X 1 : Q4) isUnit_β₀

lemma β_algebraMap (F : Q4) : β (algebraMap Q4 L F) = β₀ F := by
  simp [β]

lemma α_β : α.comp β = AlgHom.id ℚ L := by
  apply IsLocalization.algHom_ext (Submonoid.powers (X 1 : Q4))
  apply MvPolynomial.algHom_ext
  intro i
  change α (β (algebraMap Q4 L (X i))) = algebraMap Q4 L (X i)
  rw [β_algebraMap, β₀_X]
  fin_cases i
  · change α (algebraMap Astar Au t) = _
    rw [α_algebraMap, αA, lift_t]; rfl
  · change α (algebraMap Astar Au u) = _
    rw [α_algebraMap, αA, lift_u]; rfl
  · change α (algebraMap Astar Au v) = _
    rw [α_algebraMap, αA, lift_v]; rfl
  · change α (algebraMap Astar Au r₁) = _
    rw [α_algebraMap, αA, lift_r₁]; rfl

lemma β_α : β.comp α = AlgHom.id ℚ Au := by
  apply IsLocalization.algHom_ext (Submonoid.powers u)
  apply Ideal.Quotient.algHom_ext ℚ
  apply MvPolynomial.algHom_ext
  intro i
  change β (α (algebraMap Astar Au (mk (X i)))) = algebraMap Astar Au (mk (X i))
  rw [α_algebraMap]
  fin_cases i
  · change β (αA t) = algebraMap Astar Au t
    rw [αA, lift_t]
    exact (β_algebraMap _).trans (β₀_X 0)
  · change β (αA u) = algebraMap Astar Au u
    rw [αA, lift_u]
    exact (β_algebraMap _).trans (β₀_X 1)
  · change β (αA v) = algebraMap Astar Au v
    rw [αA, lift_v]
    exact (β_algebraMap _).trans (β₀_X 2)
  · -- `β((1 - r₁ v) u⁻¹) = r₀`, using `r₀ u + r₁ v = 1`
    change β (αA r₀) = algebraMap Astar Au r₀
    rw [αA, lift_r₀]
    change β ((1 - algebraMap Q4 L (X 3) * algebraMap Q4 L (X 2)) * invL) = _
    rw [map_mul, map_sub, map_one, map_mul, β_algebraMap, β_algebraMap, β₀_X, β₀_X]
    have h1 : algebraMap Astar Au u * β invL = 1 := by
      have := congrArg β mul_invL
      rwa [map_mul, map_one, β_algebraMap, β₀_X] at this
    have h2 : algebraMap Astar Au r₀ * algebraMap Astar Au u +
        algebraMap Astar Au r₁ * algebraMap Astar Au v = 1 := by
      rw [← map_mul, ← map_mul, ← map_add, rel_eq_one, map_one]
    change (1 - algebraMap Astar Au r₁ * algebraMap Astar Au v) * β invL = _
    linear_combination (algebraMap Astar Au r₀) * h1 - β invL * h2
  · change β (αA r₁) = algebraMap Astar Au r₁
    rw [αA, lift_r₁]
    exact (β_algebraMap _).trans (β₀_X 3)

/-- **`A*[u⁻¹] ≅ ℚ[t, u, u⁻¹, v, r₁]`** (`r₀ = (1 - r₁ v)/u`). -/
def equivAu : Au ≃ₐ[ℚ] L := AlgEquiv.ofAlgHom α β α_β β_α

/-- The involution of `A*` exchanging `u ↔ v` and `r₀ ↔ r₁`. -/
def swapHom : Astar →ₐ[ℚ] Astar :=
  lift ![t, v, u, r₁, r₀] (by simp only [Matrix.cons_val]; linear_combination rel_eq_one)

lemma swapHom_swapHom : swapHom.comp swapHom = AlgHom.id ℚ Astar := by
  apply algHom_ext <;> simp [swapHom]

/-- The involution `u ↔ v`, `r₀ ↔ r₁` of `A*`. -/
def swapEquiv : Astar ≃ₐ[ℚ] Astar :=
  AlgEquiv.ofAlgHom swapHom swapHom swapHom_swapHom swapHom_swapHom

lemma swapEquiv_u : swapEquiv u = v := by simp [swapEquiv, swapHom]

lemma map_powers_u :
    Submonoid.map swapEquiv.toRingEquiv.toMonoidHom (Submonoid.powers u) = Submonoid.powers v := by
  rw [Submonoid.map_powers]
  have h : swapEquiv.toRingEquiv.toMonoidHom u = v := swapEquiv_u
  rw [h]

/-- `A*[u⁻¹] ≅ A*[v⁻¹]`, induced by the involution. -/
def equivAuAv : Au ≃+* Av :=
  IsLocalization.ringEquivOfRingEquiv Au Av swapEquiv.toRingEquiv map_powers_u

/-- **`A*[v⁻¹] ≅ ℚ[t, v, v⁻¹, u, r₀]`**: the ring `L`, with its variables `X 0, X 1, X 2, X 3` now
playing the roles of `t, v, u, r₀`. -/
def equivAv : Av ≃ₐ[ℚ] L := equivAuAv.symm.toRatAlgEquiv.trans equivAu

/-! ## Smoothness -/

instance : Algebra.Smooth Q4 L := Algebra.Smooth.of_isLocalization_Away (X 1 : Q4)

/-- `ℚ[t, u, u⁻¹, v, r₁]` is smooth over `ℚ`. -/
instance L_smooth : Algebra.Smooth ℚ L := Algebra.Smooth.comp ℚ Q4 L

/-- `A*[u⁻¹]` is smooth over `ℚ`. -/
instance Au_smooth : Algebra.Smooth ℚ Au := Algebra.Smooth.of_equiv equivAu.symm

/-- `A*[v⁻¹]` is smooth over `ℚ`. -/
instance Av_smooth : Algebra.Smooth ℚ Av := Algebra.Smooth.of_equiv equivAv.symm

instance : Algebra.FinitePresentation ℚ Astar :=
  Algebra.FinitePresentation.quotient ⟨{rel}, by simp⟩

/-- **`A*` is smooth over `ℚ`**: `Spec A*` is covered by the open subsets `u ≠ 0` and `v ≠ 0`
(as `r₀ u + r₁ v = 1`), whose coordinate rings `A*[u⁻¹]` and `A*[v⁻¹]` are smooth. -/
instance Astar_smooth : Algebra.Smooth ℚ Astar := by
  have hu : ↑(PrimeSpectrum.basicOpen u) ⊆ Algebra.smoothLocus ℚ Astar :=
    Algebra.basicOpen_subset_smoothLocus_iff_smooth.2 inferInstance
  have hv : ↑(PrimeSpectrum.basicOpen v) ⊆ Algebra.smoothLocus ℚ Astar :=
    Algebra.basicOpen_subset_smoothLocus_iff_smooth.2 inferInstance
  have huniv : Algebra.smoothLocus ℚ Astar = Set.univ := by
    ext p
    simp only [Set.mem_univ, iff_true]
    by_cases hup : u ∈ p.asIdeal
    · have hvp : v ∉ p.asIdeal := by
        intro hvp
        apply p.isPrime.ne_top
        rw [Ideal.eq_top_iff_one, ← rel_eq_one]
        exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ hup) (Ideal.mul_mem_left _ _ hvp)
      exact hv (PrimeSpectrum.mem_basicOpen _ _ |>.2 hvp)
    · exact hu (PrimeSpectrum.mem_basicOpen _ _ |>.2 hup)
  exact ⟨Algebra.smoothLocus_eq_univ_iff.1 huniv, inferInstance⟩

/-! ## Factoriality -/

/-- `ℚ[t, u, u⁻¹, v, r₁]` is a UFD (a localization of a UFD). -/
instance L_ufd : UniqueFactorizationMonoid L :=
  UniqueFactorizationMonoid.of_isLocalization (Submonoid.powers (X 1 : Q4))
    (by rintro ⟨n, hn⟩; exact pow_ne_zero n (MvPolynomial.X_ne_zero 1) hn) L

/-- **`A*[u⁻¹]` is a UFD.** -/
instance Au_ufd : UniqueFactorizationMonoid Au :=
  MulEquiv.uniqueFactorizationMonoid equivAu.symm.toMulEquiv inferInstance

/-- **`A*` is factorial**, by Nagata's criterion applied to the prime element `u`. -/
instance Astar_ufd : UniqueFactorizationMonoid Astar :=
  UniqueFactorizationMonoid.of_isLocalization_away u_prime Au

/-- `A*` as a smooth finitely generated factorial `ℚ`-domain. -/
def AstarSFD : SmoothFactorialDomain := ⟨Astar⟩

/-! ## Injectivity of `φ` -/

/-- **`φ : ℚ[x, y] → A*` is injective.** The assignments `t ↦ 1`, `u ↦ x - 1`, `v ↦ y`,
`r₀ ↦ (x - 1)⁻¹`, `r₁ ↦ 0` define a homomorphism `A* → ℚ(x, y)` whose composite with `φ` is the
usual inclusion `ℚ[x, y] ⊆ ℚ(x, y)`. -/
theorem φ_injective : Function.Injective φ := by
  set K := FractionRing A₀
  have hx1 : (x - 1 : A₀) ≠ 0 := by
    intro h
    have := congrArg (MvPolynomial.eval (fun _ => (0 : ℚ))) h
    simp [x] at this
  have hK : algebraMap A₀ K (x - 1) ≠ 0 := fun h =>
    hx1 (IsFractionRing.injective A₀ K (by rw [h, map_zero]))
  let ev : Astar →ₐ[ℚ] K := lift ![1, algebraMap A₀ K (x - 1), algebraMap A₀ K y,
    (algebraMap A₀ K (x - 1))⁻¹, 0] (by
      simp only [Matrix.cons_val, zero_mul, add_zero]
      exact inv_mul_cancel₀ hK)
  have hcomp : (ev : Astar →+* K).comp (φ : A₀ →+* Astar) = algebraMap A₀ K := by
    apply MvPolynomial.ringHom_ext
    · intro q
      have h1 := eq_ratCast (((ev : Astar →+* K).comp (φ : A₀ →+* Astar)).comp C) q
      have h2 := eq_ratCast ((algebraMap A₀ K).comp C) q
      simp only [RingHom.comp_apply] at h1 h2
      rw [RingHom.comp_apply, h1, h2]
    · intro i
      fin_cases i
      · change ev (φ x) = algebraMap A₀ K x
        simp [ev, map_sub]
      · change ev (φ y) = algebraMap A₀ K y
        simp [ev]
  intro a b hab
  apply IsFractionRing.injective A₀ K
  have h := congrArg ev hab
  have ha : ev (φ a) = algebraMap A₀ K a := congrArg (fun g : A₀ →+* K => g a) hcomp
  have hb : ev (φ b) = algebraMap A₀ K b := congrArg (fun g : A₀ →+* K => g b) hcomp
  rw [← ha, ← hb]
  exact h

end BezoutCounterexample.Explicit
