import BezoutCounterexample.Construction

/-!
# Lemma 5.3 and Theorem 1.1

This file formalizes the end of Section 5 of the paper:

* **Lemma 5.3** (`lem:key-obstruction`, `key_obstruction`): there are no `p, q, u, v, μ, c ∈ R`
  with `μ (p, q) M (u, v)ᵀ = 1 + Δ c`. The row-matrix-column product `(p, q) M (u, v)ᵀ` is written
  `![p, q] ᵥ* M ⬝ᵥ ![u, v]` (`Matrix.vecMul` and `dotProduct`).
* **Theorem 1.1** (`thm:main`, `main_theorem`): there is a countable Bézout domain `R` containing
  `A₀` (via an injection `ι : A₀ ↪ R`) such that `Δ` is a nonzero nonunit of `R` and `M` has no
  Smith normal form over `R`; consequently `R` has characteristic zero and is not an elementary
  divisor domain. For the ring `R` of Construction 5.1 these are `bezout_domain`,
  `not_hasSmithNormalForm` and `not_isElementaryDivisorDomain`.

The proofs follow the paper: for Lemma 5.3, all six elements lie in some `A_N`, and evaluating at
the points of `K_N` produces the nowhere-zero section `ξ(z) = M(z) (u(z), v(z))ᵀ` of `L_N`,
contradicting (5.2); for Theorem 1.1, a Smith normal form `P M Q = diag(d₁, d₂)` forces `d₁` to be a
unit, and then the first row of `P` and the first column of `Q` contradict Lemma 5.3 with
`μ = d₁⁻¹` and `c = 0`.
-/

noncomputable section

namespace BezoutCounterexample

open Set Topology Matrix Construction

/-- The product `(p, q) M (u, v)ᵀ`, written out. -/
lemma vecMul_M_dotProduct {S : Type*} [CommRing S] (φ : A₀ →+* S) (p q u v : S) :
    ![p, q] ᵥ* (M.map φ) ⬝ᵥ ![u, v] =
      (p * (1 + φ x) + q * φ y) * u + (p * φ y + q * (1 - φ x)) * v := by
  simp [Matrix.vecMul, dotProduct, Fin.sum_univ_two, M]

/-- **Lemma 5.3** (`lem:key-obstruction`). There are no elements `p, q, u, v, μ, c ∈ R` such that
`μ (p, q) M (u, v)ᵀ = 1 + Δ c`.

Proof: choose `N` such that all six elements lie in `A_N`; the identity already holds in `A_N`
because `A_N ↪ R` is injective. At `z ∈ K_N` we have `Δ(z) = 0`, so the vector
`ξ(z) = M(z) (u(z), v(z))ᵀ ∈ L_N(z)` satisfies `μ(z) (p(z), q(z)) ξ(z) = 1`, hence `ξ(z) ≠ 0`.
It depends continuously on `z`, so `ξ` is a continuous nowhere-zero section of `L_N`,
contradicting (5.2). -/
theorem key_obstruction :
    ¬ ∃ p q u v μ c : R, μ * (![p, q] ᵥ* (M.map R.ι) ⬝ᵥ ![u, v]) = 1 + R.ι Δ * c := by
  rintro ⟨p, q, u, v, μ, c, hrel⟩
  -- all six elements lie in some `A_N`
  obtain ⟨N, w, hw⟩ := R.exists_of_fin 6 ![p, q, u, v, μ, c]
  -- the identity already holds in `A_N`
  have hrelN : w 4 * (![w 0, w 1] ᵥ* (M.map (ι N)) ⬝ᵥ ![w 2, w 3]) = 1 + ι N Δ * w 5 := by
    apply R.of_injective N
    have e : ∀ t, R.of N (w t) = ![p, q, u, v, μ, c] t := hw
    simp only [vecMul_M_dotProduct, map_mul, map_add, map_sub, map_one, R.of_ι, e] at hrel ⊢
    simpa using hrel
  rw [vecMul_M_dotProduct] at hrelN
  -- the section `ξ(z) = M(z) (u(z), v(z))ᵀ` of `L_N`
  apply nonorientable N
  have hc : ∀ a : A N, Continuous fun z : K N => z.1 a :=
    fun a => (RealPt.continuous_eval a).comp continuous_subtype_val
  refine ⟨fun z => (Mreal (z.1 (ι N x)) (z.1 (ι N y))).mulVec ![z.1 (w 2), z.1 (w 3)], ?_,
    fun z => ⟨?_, mem_lineBundle_iff.2 ⟨_, rfl⟩⟩⟩
  · -- `ξ` is continuous
    refine continuous_pi fun i => ?_
    fin_cases i <;> simp only [Mreal_mulVec] <;> simp <;> fun_prop
  · -- `ξ(z) ≠ 0`, since `μ(z) (p(z), q(z)) ξ(z) = 1`
    intro h0
    have h := congrArg z.1 hrelN
    simp only [map_mul, map_add, map_sub, map_one, Δ_eq_zero N z.2, zero_mul, add_zero] at h
    have h1 := congrFun h0 0
    have h2 := congrFun h0 1
    simp only [Mreal_mulVec, Matrix.cons_val_zero, Matrix.cons_val_one, Pi.zero_apply] at h1 h2
    have : z.1 (w 4) * (z.1 (w 0) * ((1 + z.1 (ι N x)) * z.1 (w 2) + z.1 (ι N y) * z.1 (w 3)) +
        z.1 (w 1) * (z.1 (ι N y) * z.1 (w 2) + (1 - z.1 (ι N x)) * z.1 (w 3))) = 1 := by
      linear_combination h
    rw [h1, h2, mul_zero, mul_zero, add_zero, mul_zero] at this
    exact zero_ne_one this

/-- By (2.1), the entries `1 + x`, `y`, `1 - x` of `M` generate `R`. -/
theorem span_entries_M_map : (Ideal.span {R.ι (1 + x), R.ι y, R.ι (1 - x)} : Ideal R) = ⊤ := by
  have h := congrArg (Ideal.map R.ι) span_entries_M
  rwa [Ideal.map_span, Ideal.map_top, Set.image_insert_eq, Set.image_pair] at h

/-- **Theorem 1.1**, the main point: `M` has no Smith normal form over `R`.

Suppose `P M Q = diag(d₁, d₂)` with `P, Q ∈ GL₂(R)` and `d₁ ∣ d₂`. Multiplication by invertible
matrices preserves the ideal generated by all entries, and by (2.1) the entries of `M` generate `R`;
thus `(d₁, d₂) = R`. Since `d₁ ∣ d₂`, this ideal is `(d₁)`, so `d₁` is a unit. If `(p, q)` is the
first row of `P` and `(u, v)ᵀ` the first column of `Q`, then `(p, q) M (u, v)ᵀ = d₁`, so `μ = d₁⁻¹`
and `c = 0` contradict Lemma 5.3. -/
theorem not_hasSmithNormalForm : ¬ HasSmithNormalForm (M.map R.ι) := by
  rintro ⟨G, hMG, hG⟩
  -- `G = diag(d₁, d₂)` with `d₁ ∣ d₂`
  obtain ⟨d, hd, hdiv⟩ := (isSmithNormalForm_iff_chain G).1 hG
  have hd12 : d 0 ∣ d 1 := hdiv 0 (by norm_num)
  -- `(d₁, d₂) = R`
  have htop : (Ideal.span {d 0, d 1} : Ideal R) = ⊤ := by
    have hGmem : ∀ i j, G i j ∈ (Ideal.span {d 0, d 1} : Ideal R) := by
      intro i j
      fin_cases i <;> fin_cases j
      · rw [hd]; exact Ideal.subset_span (by simp)
      · rw [hd]; simp
      · rw [hd]; simp
      · rw [hd]; exact Ideal.subset_span (by simp)
    have hM := hMG.entry_mem _ hGmem
    rw [eq_top_iff, ← span_entries_M_map, Ideal.span_le]
    rintro r (rfl | rfl | rfl)
    · simpa [M] using hM 0 0
    · simpa [M] using hM 0 1
    · simpa [M] using hM 1 1
  -- since `d₁ ∣ d₂`, `(d₁, d₂) = (d₁)`, so `d₁` is a unit
  have hunit : IsUnit (d 0) := by
    have h : (Ideal.span {d 0, d 1} : Ideal R) = Ideal.span {d 0} := by
      rw [Ideal.span_insert, sup_eq_left.2 (Ideal.span_singleton_le_span_singleton.2 hd12)]
    rwa [h, Ideal.span_singleton_eq_top] at htop
  -- the first row `(p, q)` of `P` and the first column `(u, v)ᵀ` of `Q`
  obtain ⟨P, Q, hPQ⟩ := hMG
  have h00 : ![(P : Matrix (Fin 2) (Fin 2) R) 0 0, (P : Matrix (Fin 2) (Fin 2) R) 0 1] ᵥ*
      (M.map R.ι) ⬝ᵥ ![(Q : Matrix (Fin 2) (Fin 2) R) 0 0, (Q : Matrix (Fin 2) (Fin 2) R) 1 0] =
      d 0 := by
    have h : ((P : Matrix (Fin 2) (Fin 2) R) * M.map R.ι * Q) 0 0 = d 0 := by
      rw [hPQ, hd]; simp
    rw [← h]
    simp only [Matrix.mul_apply, Fin.sum_univ_two, Matrix.vecMul, dotProduct]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one]
  obtain ⟨μ, hμ⟩ := hunit.exists_left_inv
  exact key_obstruction ⟨_, _, _, _, μ, 0, by rw [h00, hμ, mul_zero, add_zero]⟩

/-- **Theorem 1.1**: `R` is not an elementary divisor domain, since the `2 × 2` matrix `M` has no
Smith normal form over `R`. -/
theorem not_isElementaryDivisorDomain : ¬ IsElementaryDivisorDomain R :=
  fun h => not_hasSmithNormalForm (h.2 2 2 _)

/-- **Theorem 1.1** (`thm:main`). There exists a countable Bézout domain `R` containing `A₀`
(i.e. with an injective ring homomorphism `ι : A₀ → R`) such that `Δ` is a nonzero nonunit of `R`
and `M` has no Smith normal form over `R`. Consequently, `R` has characteristic zero and is not an
elementary divisor domain.

The ring is the ring `R` of Construction 5.1: Proposition 5.2 (`bezout_domain`) proves all
assertions except the failure of Smith normal form, which is `not_hasSmithNormalForm`. -/
theorem main_theorem :
    ∃ (R : Type) (_ : CommRing R) (_ : IsDomain R) (ι : A₀ →+* R),
      Countable R ∧ IsBezout R ∧ Function.Injective ι ∧ ι Δ ≠ 0 ∧ ¬ IsUnit (ι Δ) ∧
      ¬ HasSmithNormalForm (M.map ι) ∧ CharZero R ∧ ¬ IsElementaryDivisorDomain R :=
  ⟨R, inferInstance, R.isDomain, R.ι, R.countable, R.isBezout, R.ι_injective, R.Δ_ne_zero,
    R.Δ_not_isUnit, not_hasSmithNormalForm, R.charZero, not_isElementaryDivisorDomain⟩

end BezoutCounterexample
