import BezoutCounterexample.MainTheorem

/-!
# Proposition 6.1: a nonfree rank-one projective module

This file formalizes **Proposition 6.1** (`prop:quotient-module`) of the paper: let `B = R/(Δ)`
and let `M̄` be the image of `M` in `M₂(B)`. Then `Π = ½ M̄` is an idempotent, and `Π B²` is a
nonfree projective `B`-module of constant rank one generated by two elements.

* A finitely generated projective module has *constant rank one* if its tensor product with the
  residue field at every prime ideal is one-dimensional (`HasConstantRankOne`).
* `B`, `Mbar` (`M̄`) and `PiMat` (the idempotent `Π = ½ M̄`; the letter `Π` is reserved notation in
  Lean) are defined below, and `imageModule PiMat` is the module `Π B² ⊆ B²`, the range of
  `w ↦ Π w`.
* `quotient_module` (**Proposition 6.1**) collects: `B` is nonzero (`B_nontrivial`), `Π² = Π`
  (`PiMat_idempotent`, from (2.1)), `B² = Π B² ⊕ (1 - Π) B²` (`isCompl_imageModule`), `Π B²` is
  projective (`imageModule_projective`), it has constant rank one (`PiMat_hasConstantRankOne`: over
  a residue field, `Π` is an idempotent of trace one, hence of rank one), it is generated by the two
  columns of `Π` (`span_projIm_single`), and it is not free (`imageModule_PiMat_not_free`).

The proof of non-freeness follows the paper: if `Π B²` were free, it would be free of rank one
(it has constant rank one and `B ≠ 0`); a basis vector `b` and the composite of `Π : B² → Π B²`
with the isomorphism `Π B² → B`, `b ↦ 1`, give a row vector `λ` with `Π = b λ` and `λ b = 1`
(`exists_rank_one_factorization`). Then `λ M̄ b = 2`, and lifting `λ` and `b` to `R` contradicts
Lemma 5.3 with `μ = ½`.
-/

noncomputable section

namespace BezoutCounterexample

open Module TensorProduct Matrix

/-- A module `P` over a ring `B` has *constant rank one* if its tensor product
`κ(𝔭) ⊗_B P` with the residue field at every prime ideal `𝔭` (the fibre `𝔭.Fiber P`) is
one-dimensional. -/
def HasConstantRankOne (B : Type*) [CommRing B] (P : Type*) [AddCommGroup P] [Module B P] :
    Prop :=
  ∀ (𝔭 : Ideal B) [𝔭.IsPrime], finrank 𝔭.ResidueField (𝔭.ResidueField ⊗[B] P) = 1

/-! ## Images of idempotent `2 × 2` matrices -/

section Idempotent

variable {B : Type*} [CommRing B] (E : Matrix (Fin 2) (Fin 2) B)

/-- The module `E B² ⊆ B²`, the image of `w ↦ E w`. -/
abbrev imageModule : Submodule B (Fin 2 → B) := LinearMap.range E.mulVecLin

/-- The map `E : B² → E B²`. -/
def projIm : (Fin 2 → B) →ₗ[B] imageModule E := E.mulVecLin.rangeRestrict

variable {E}

lemma projIm_apply_coe (w : Fin 2 → B) : (projIm E w : Fin 2 → B) = E *ᵥ w := rfl

lemma projIm_comp_subtype (hE : IsIdempotentElem E) :
    projIm E ∘ₗ (imageModule E).subtype = LinearMap.id := by
  ext ⟨v, w, rfl⟩ : 1
  apply Subtype.ext
  simp only [LinearMap.comp_apply, Submodule.subtype_apply, LinearMap.id_apply, projIm_apply_coe,
    Matrix.mulVecLin_apply, Matrix.mulVec_mulVec, hE.eq]

lemma subtype_comp_projIm : (imageModule E).subtype ∘ₗ projIm E = E.mulVecLin :=
  LinearMap.ext fun _ => rfl

/-- For an idempotent `E`, `B² = E B² ⊕ (1 - E) B²`. -/
theorem isCompl_imageModule (hE : IsIdempotentElem E) :
    IsCompl (imageModule E) (imageModule (1 - E)) := by
  constructor
  · rw [Submodule.disjoint_def]
    rintro w ⟨a, rfl⟩ ⟨b, hb⟩
    simp only [Matrix.mulVecLin_apply] at hb ⊢
    have h1 : E *ᵥ (E *ᵥ a) = E *ᵥ a := by rw [Matrix.mulVec_mulVec, hE.eq]
    have h2 : E *ᵥ ((1 - E) *ᵥ b) = 0 := by
      rw [Matrix.mulVec_mulVec, Matrix.mul_sub, Matrix.mul_one, hE.eq, sub_self,
        Matrix.zero_mulVec]
    rw [← h1, ← hb, h2]
  · rw [codisjoint_iff, eq_top_iff]
    intro w _
    have hw : w = E *ᵥ w + (1 - E) *ᵥ w := by
      rw [Matrix.sub_mulVec, Matrix.one_mulVec]; abel
    rw [hw]
    exact Submodule.add_mem_sup ⟨w, rfl⟩ ⟨w, rfl⟩

/-- `E B²` is projective, being a direct summand of `B²`. -/
theorem imageModule_projective (hE : IsIdempotentElem E) : Module.Projective B (imageModule E) :=
  Module.Projective.of_split _ _ (projIm_comp_subtype hE)

/-- `E B²` is generated by the two columns `E e₁`, `E e₂` of `E`. -/
theorem span_projIm_single (E : Matrix (Fin 2) (Fin 2) B) :
    Submodule.span B (Set.range fun j : Fin 2 => projIm E (Pi.single j 1)) = ⊤ := by
  have h : (Set.range fun j : Fin 2 => projIm E (Pi.single j 1)) =
      projIm E '' Set.range (Pi.basisFun B (Fin 2)) := by
    rw [← Set.range_comp]
    congr 1
    funext j
    simp [Pi.basisFun_apply]
  rw [h, ← Submodule.map_span, (Pi.basisFun B (Fin 2)).span_eq, Submodule.map_top, projIm,
    LinearMap.range_rangeRestrict]

lemma rank_pos_of_ne_zero' {k : Type*} [Field k] {A : Matrix (Fin 2) (Fin 2) k} (h : A ≠ 0) :
    0 < A.rank := by
  rw [Nat.pos_iff_ne_zero]
  intro h0
  apply h
  rw [Matrix.rank, Submodule.finrank_eq_zero, LinearMap.range_eq_bot] at h0
  ext i j
  have := congrArg (fun f => f (Pi.single j 1) i) h0
  simpa [Matrix.mulVec_single] using this

/-- An idempotent `2 × 2` matrix of trace one over a field has rank one. -/
theorem rank_eq_one_of_idempotent {k : Type*} [Field k] {A : Matrix (Fin 2) (Fin 2) k}
    (hA : IsIdempotentElem A) (htr : A.trace = 1) : A.rank = 1 := by
  have h1 : A * (1 - A) = 0 := by rw [Matrix.mul_sub, Matrix.mul_one, hA.eq, sub_self]
  have hsum := Matrix.rank_add_rank_le_card_of_mul_eq_zero h1
  have hA0 : A ≠ 0 := by
    intro h; rw [h, Matrix.trace_zero] at htr; exact zero_ne_one htr
  have hB0 : (1 - A) ≠ 0 := by
    intro h
    have := congrArg Matrix.trace h
    rw [Matrix.trace_sub, htr, Matrix.trace_one, Matrix.trace_zero, Fintype.card_fin] at this
    norm_num at this
  have r1 := rank_pos_of_ne_zero' hA0
  have r2 := rank_pos_of_ne_zero' hB0
  simp only [Fintype.card_fin] at hsum
  omega

variable (k : Type*) [Field k] [Algebra B k]

lemma piScalarRight_comp_baseChange :
    (piScalarRight B k k (Fin 2)).toLinearMap ∘ₗ E.mulVecLin.baseChange k =
      (E.map (algebraMap B k)).mulVecLin ∘ₗ (piScalarRight B k k (Fin 2)).toLinearMap := by
  apply TensorProduct.AlgebraTensorModule.ext
  intro c w
  funext i
  simp only [LinearMap.coe_comp, LinearEquiv.coe_coe, Function.comp_apply,
    LinearMap.baseChange_tmul, piScalarRight_apply, piScalarRightHom_tmul,
    Matrix.mulVecLin_apply]
  simp only [Matrix.mulVec, dotProduct, Fin.sum_univ_two, Matrix.map_apply,
    Algebra.smul_def, map_add, map_mul]
  ring

/-- After base change to a field `k`, the dimension of `k ⊗ E B²` is the rank of `E` over `k`. -/
theorem finrank_baseChange_imageModule (hE : IsIdempotentElem E) :
    finrank k (k ⊗[B] imageModule E) = (E.map (algebraMap B k)).rank := by
  set i := (imageModule E).subtype
  set s := projIm E
  set ik := i.baseChange k
  set sk := s.baseChange k
  have hsik : sk ∘ₗ ik = LinearMap.id := by
    rw [← LinearMap.baseChange_comp, projIm_comp_subtype hE, LinearMap.baseChange_id]
  have hinj : Function.Injective ik := by
    intro a b hab
    have := congrArg sk hab
    rwa [← LinearMap.comp_apply, hsik, ← LinearMap.comp_apply, hsik] at this
  have hrange : LinearMap.range ik = LinearMap.range (E.mulVecLin.baseChange k) := by
    rw [← subtype_comp_projIm, LinearMap.baseChange_comp]
    apply le_antisymm
    · have : ik = (ik ∘ₗ sk) ∘ₗ ik := by rw [LinearMap.comp_assoc, hsik, LinearMap.comp_id]
      conv_lhs => rw [this]
      exact LinearMap.range_comp_le_range _ _
    · exact LinearMap.range_comp_le_range _ _
  rw [← LinearMap.finrank_range_of_inj hinj, hrange]
  set e := piScalarRight B k k (Fin 2)
  rw [← LinearEquiv.finrank_map_eq e, ← LinearMap.range_comp, piScalarRight_comp_baseChange,
    LinearMap.range_comp_of_range_eq_top _ (LinearEquiv.range e)]
  rfl

/-- **The rank-one factorization.** Let `B` be nonzero and `E` idempotent with `E B²` free of
constant rank one. Then `E B²` is free of rank one; choosing a basis vector `b` and composing
`E : B² → E B²` with the isomorphism `E B² → B`, `b ↦ 1`, gives a row vector `λ` with `E = b λ`
and `λ b = 1`. -/
theorem exists_rank_one_factorization [Nontrivial B] (hE : IsIdempotentElem E)
    (hrank : HasConstantRankOne B (imageModule E)) [Module.Free B (imageModule E)] :
    ∃ b l : Fin 2 → B, (∀ i j, E i j = b i * l j) ∧ l 0 * b 0 + l 1 * b 1 = 1 := by
  have : Module.Finite B (imageModule E) := Module.Finite.range _
  -- since `E B²` has constant rank one, it is free of rank one
  obtain ⟨𝔪, h𝔪⟩ := Ideal.exists_maximal B
  have := h𝔪.isPrime
  have h1 : finrank B (imageModule E) = 1 := by
    have := hrank 𝔪
    rwa [Module.finrank_baseChange] at this
  -- a basis vector `b`
  let bas : Basis (Fin 1) B (imageModule E) := Module.finBasisOfFinrankEq B _ h1
  set s := projIm E
  have hsi : ∀ p : imageModule E, s p = p := fun p =>
    congrArg (fun f => f p) (projIm_comp_subtype hE)
  have hrepr : ∀ p : imageModule E, p = bas.repr p 0 • bas 0 := by
    intro p
    conv_lhs => rw [← bas.sum_repr p]
    simp
  -- the row vector `λ` of the composite `B² → E B² ≅ B`
  refine ⟨(bas 0 : Fin 2 → B), fun j => bas.repr (s (Pi.single j 1)) 0, fun i j => ?_, ?_⟩
  · -- `E = b λ`
    have hcol : (s (Pi.single j 1) : Fin 2 → B) i = E i j := by
      simp [s, projIm_apply_coe, Matrix.mulVec_single]
    rw [← hcol, hrepr (s (Pi.single j 1))]
    simp [mul_comm]
  · -- `λ b = 1`, since `E b = b`
    have hb : (bas 0 : Fin 2 → B) =
        (bas 0 : Fin 2 → B) 0 • Pi.single 0 1 + (bas 0 : Fin 2 → B) 1 • Pi.single 1 1 := by
      ext i
      fin_cases i <;> simp
    have h2 : bas.repr (s (Pi.single 0 1)) 0 * (bas 0 : Fin 2 → B) 0 +
        bas.repr (s (Pi.single 1 1)) 0 * (bas 0 : Fin 2 → B) 1 =
          bas.repr (s (bas 0 : Fin 2 → B)) 0 := by
      conv_rhs => rw [hb]
      simp [mul_comm]
    rw [h2, hsi, bas.repr_self, Finsupp.single_eq_same]

end Idempotent

/-! ## The module `Π B²` over `B = R/(Δ)` -/

/-- The ring `B = R/(Δ)`. -/
abbrev B : Type := R ⧸ Ideal.span {R.ι Δ}

/-- The quotient map `R → B`. -/
abbrev toB : R →+* B := Ideal.Quotient.mk _

/-- `M̄`, the image of `M` in `M₂(B)`. -/
def Mbar : Matrix (Fin 2) (Fin 2) B := M.map (toB.comp R.ι)

/-- The idempotent `Π = ½ M̄ ∈ M₂(B)`. -/
def PiMat : Matrix (Fin 2) (Fin 2) B := (2⁻¹ : ℚ) • Mbar

/-- `B` is nonzero, because `Δ` is not a unit of `R`. -/
instance B_nontrivial : Nontrivial B := by
  apply Ideal.Quotient.nontrivial_iff.2
  rw [Ne, Ideal.span_singleton_eq_top]
  exact R.Δ_not_isUnit

lemma toB_Δ : toB (R.ι Δ) = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.subset_span rfl)

lemma two_mul_half : (2 : B) * algebraMap ℚ B 2⁻¹ = 1 := by
  rw [← map_ofNat (algebraMap ℚ B) 2, ← map_mul]
  norm_num

lemma PiMat_apply (i j : Fin 2) : PiMat i j = algebraMap ℚ B 2⁻¹ * Mbar i j := by
  rw [PiMat, Matrix.smul_apply, Algebra.smul_def]

/-- `M̄ = 2 Π`. -/
lemma Mbar_eq_two_mul (i j : Fin 2) : Mbar i j = 2 * PiMat i j := by
  rw [PiMat_apply, ← mul_assoc, two_mul_half, one_mul]

/-- `M̄² = 2 M̄`, the image of `M² - 2M = Δ I₂` from (2.1). -/
lemma Mbar_mul_self : Mbar * Mbar = (2 : B) • Mbar := by
  ext i j
  have h := congrArg (fun N : Matrix (Fin 2) (Fin 2) A₀ => toB (R.ι (N i j))) M_sq
  simp only [Matrix.sub_apply, Matrix.smul_apply, Matrix.mul_apply, Fin.sum_univ_two, smul_eq_mul,
    map_sub, map_add, map_mul, toB_Δ, zero_mul] at h
  simp only [Mbar, Matrix.mul_apply, Fin.sum_univ_two, Matrix.map_apply, Matrix.smul_apply,
    smul_eq_mul, RingHom.comp_apply]
  rw [map_ofNat, map_ofNat] at h
  linear_combination h

/-- **`Π² = Π`**, by (2.1). -/
theorem PiMat_idempotent : IsIdempotentElem PiMat := by
  unfold IsIdempotentElem
  ext i j
  have h := congrFun (congrFun Mbar_mul_self i) j
  simp only [Matrix.mul_apply, Fin.sum_univ_two, Matrix.smul_apply, smul_eq_mul] at h ⊢
  simp only [PiMat_apply]
  linear_combination (algebraMap ℚ B 2⁻¹) ^ 2 * h + (algebraMap ℚ B 2⁻¹ * Mbar i j) * two_mul_half

/-- The trace of `Π` is one. -/
lemma PiMat_trace : PiMat.trace = 1 := by
  rw [Matrix.trace_fin_two, PiMat_apply, PiMat_apply]
  simp [Mbar, M]
  linear_combination two_mul_half

/-- **`Π B²` has constant rank one**: after base change to any residue field of `B`, `Π` is an
idempotent of trace one and therefore has rank one. -/
theorem PiMat_hasConstantRankOne : HasConstantRankOne B (imageModule PiMat) := by
  intro 𝔭 _
  rw [finrank_baseChange_imageModule _ PiMat_idempotent]
  apply rank_eq_one_of_idempotent
  · unfold IsIdempotentElem
    rw [← Matrix.map_mul, PiMat_idempotent.eq]
  · rw [Matrix.trace, ← map_one (algebraMap B 𝔭.ResidueField), ← PiMat_trace, Matrix.trace,
      map_sum]
    rfl

/-- **`Π B²` is not free.** If it were, it would be free of rank one, and a basis vector `b` would
give a row vector `λ` with `Π = b λ`, `λ b = 1` (`exists_rank_one_factorization`). Since `M̄ = 2 Π`,
`λ M̄ b = 2`. Lifting `λ` to `(p, q)` and `b` to `(u, v)ᵀ` over `R`, we get
`½ (p, q) M (u, v)ᵀ - 1 = Δ c` for some `c ∈ R`, contradicting Lemma 5.3 with `μ = ½`. -/
theorem imageModule_PiMat_not_free : ¬ Module.Free B (imageModule PiMat) := by
  intro hfree
  obtain ⟨b, l, hfac, hlb⟩ :=
    exists_rank_one_factorization PiMat_idempotent PiMat_hasConstantRankOne
  -- `λ M̄ b = 2`
  have hMb : ![l 0, l 1] ᵥ* Mbar ⬝ᵥ ![b 0, b 1] = 2 := by
    simp only [Matrix.vecMul, dotProduct, Fin.sum_univ_two, Matrix.cons_val_zero,
      Matrix.cons_val_one, Mbar_eq_two_mul, hfac]
    linear_combination (2 * (l 0 * b 0 + l 1 * b 1) + 2) * hlb
  -- lifts of `λ` and `b` to `R`
  obtain ⟨p, hp⟩ := Ideal.Quotient.mk_surjective (l 0)
  obtain ⟨q, hq⟩ := Ideal.Quotient.mk_surjective (l 1)
  obtain ⟨u, hu⟩ := Ideal.Quotient.mk_surjective (b 0)
  obtain ⟨v, hv⟩ := Ideal.Quotient.mk_surjective (b 1)
  -- `½ (p, q) M (u, v)ᵀ - 1 ∈ (Δ)`
  have hmem : algebraMap ℚ R 2⁻¹ * (![p, q] ᵥ* (M.map R.ι) ⬝ᵥ ![u, v]) - 1 ∈
      Ideal.span {R.ι Δ} := by
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, map_mul, map_one, Ideal.Quotient.mk_algebraMap]
    have h1 : toB (![p, q] ᵥ* (M.map R.ι) ⬝ᵥ ![u, v]) = ![l 0, l 1] ᵥ* Mbar ⬝ᵥ ![b 0, b 1] := by
      rw [vecMul_M_dotProduct, Mbar, vecMul_M_dotProduct]
      simp only [map_add, map_mul, map_sub, map_one, RingHom.comp_apply]
      rw [hp, hq, hu, hv]
    rw [h1, hMb, mul_comm, two_mul_half, sub_self]
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.1 hmem
  exact key_obstruction ⟨p, q, u, v, algebraMap ℚ R 2⁻¹, c, by linear_combination -hc⟩

/-- **Proposition 6.1** (`prop:quotient-module`). Let `B = R/(Δ)` and let `M̄` be the image of `M`
in `M₂(B)`. Then `Π = ½ M̄` is an idempotent, and `Π B²` is a nonfree projective `B`-module of
constant rank one generated by two elements. We also record that `B` is nonzero and that
`B² = Π B² ⊕ (1 - Π) B²`. -/
theorem quotient_module :
    Nontrivial B ∧ IsIdempotentElem PiMat ∧
      IsCompl (imageModule PiMat) (imageModule (1 - PiMat)) ∧
      Module.Projective B (imageModule PiMat) ∧ HasConstantRankOne B (imageModule PiMat) ∧
      (∃ g : Fin 2 → imageModule PiMat, Submodule.span B (Set.range g) = ⊤) ∧
      ¬ Module.Free B (imageModule PiMat) :=
  ⟨B_nontrivial, PiMat_idempotent, isCompl_imageModule PiMat_idempotent,
    imageModule_projective PiMat_idempotent, PiMat_hasConstantRankOne,
    ⟨_, span_projIm_single PiMat⟩, imageModule_PiMat_not_free⟩

end BezoutCounterexample
