import BezoutCounterexample.Principalization.Chart

/-!
# Order duality

For a centred chart of a Noetherian local `ℚ`-algebra: membership in the ideal generated by some
chart functions, and in weighted monomial ideals `F_j(w)`, is detected by the Taylor coefficients
(`Chart.IsCentred.mem_span_iff`, `Chart.IsCentred.mem_F_iff`). Foundations for Theorem 3.3
(`thm:invariant`) of the paper.
-/

noncomputable section


namespace BezoutCounterexample.Principalization

open MvPowerSeries IsLocalRing

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ}

omit [Algebra ℚ R] in
lemma prod_pow_add_single (x : Fin n → R) (α : Fin n →₀ ℕ) (j : Fin n) :
    ∏ i, x i ^ (α + Finsupp.single j 1 : Fin n →₀ ℕ) i = (∏ i, x i ^ α i) * x j := by
  simp only [Finsupp.add_apply, pow_add, Finset.prod_mul_distrib]
  congr 1
  rw [Finset.prod_eq_single j]
  · simp
  · intro i _ hi; simp [Finsupp.single_apply, Ne.symm hi]
  · simp

namespace Chart

variable (c : Chart R n)

/-- Monomials of degree `N` in the chart functions. -/
def monos (N : ℕ) : Set R := {f | ∃ α : Fin n →₀ ℕ, α.degree = N ∧ f = ∏ i, c.x i ^ α i}

variable [IsLocalRing R] {c}

lemma IsCentred.pow_eq_span (hc : c.IsCentred) (N : ℕ) :
    maximalIdeal R ^ N = Ideal.span (c.monos N) := by
  induction N with
  | zero =>
    rw [pow_zero, Ideal.one_eq_top, eq_comm, Ideal.eq_top_iff_one]
    exact Ideal.subset_span ⟨0, by simp, by simp⟩
  | succ N ih =>
    rw [pow_succ, ih, hc, Ideal.span_mul_span]
    congr 1
    ext f
    simp only [Set.mem_mul, monos, Set.mem_setOf_eq, Set.mem_range]
    constructor
    · rintro ⟨a, ⟨α, hα, rfl⟩, b, ⟨j, rfl⟩, rfl⟩
      exact ⟨α + Finsupp.single j 1, by simp [hα], (prod_pow_add_single _ _ _).symm⟩
    · rintro ⟨α, hα, rfl⟩
      obtain ⟨j, hj⟩ : ∃ j, α j ≠ 0 := by
        by_contra h; push_neg at h
        have : α = 0 := Finsupp.ext h
        subst this; simp at hα
      set α' := α - Finsupp.single j 1 with hα'
      have hsum : α' + Finsupp.single j 1 = α := by
        ext l
        simp only [hα', Finsupp.coe_add, Finsupp.coe_tsub, Pi.add_apply, Pi.sub_apply,
          Finsupp.single_apply]
        split_ifs with h
        · subst h; omega
        · omega
      refine ⟨_, ⟨α', ?_, rfl⟩, _, ⟨j, rfl⟩, ?_⟩
      · have := congrArg Finsupp.degree hsum
        rw [map_add, hα, Finsupp.degree_single] at this
        omega
      · rw [← prod_pow_add_single, hsum]

/-- In a power series ring, elements of the ideal generated by `Xᵢ` (`i ∈ S`) have vanishing
coefficients at multi-indices supported off `S`. -/
lemma coeff_eq_zero_of_mem_span_X {K : Type*} [CommRing K] (S : Set (Fin n))
    {Φ : MvPowerSeries (Fin n) K} (hΦ : Φ ∈ Ideal.span (X '' S)) (δ : Fin n →₀ ℕ)
    (hδ : ∀ i ∈ S, δ i = 0) : coeff δ Φ = 0 := by
  classical
  revert δ
  induction hΦ using Submodule.span_induction with
  | mem Ψ hΨ =>
    intro δ hδ
    obtain ⟨i, hi, rfl⟩ := hΨ
    rw [coeff_X]; split_ifs with h
    · subst h; simpa using hδ i hi
    · rfl
  | zero => intros; simp
  | add _ _ _ _ h1 h2 => intro δ hδ; rw [map_add, h1 δ hδ, h2 δ hδ, add_zero]
  | smul a Ψ _ h =>
    intro δ hδ
    rw [smul_eq_mul, coeff_mul, Finset.sum_eq_zero]
    intro p hp
    rw [Finset.HasAntidiagonal.mem_antidiagonal] at hp
    have : ∀ i ∈ S, p.2 i = 0 := fun i hi => by
      have := congrArg (fun q => q i) hp
      simp only [Finsupp.coe_add, Pi.add_apply, hδ i hi] at this
      omega
    rw [h p.2 this, mul_zero]

end Chart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries IsLocalRing

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ} [IsLocalRing R] {c : Chart R n}

namespace Chart

omit [IsLocalRing R] in
lemma _root_.BezoutCounterexample.Principalization.Finsupp.eq_of_le_of_degree_eq
    {α α' : Fin n →₀ ℕ} (hle : α' ≤ α) (hdeg : α'.degree = α.degree) : α' = α := by
  have h1 : α' + (α - α') = α := add_tsub_cancel_of_le hle
  have h2 := congrArg Finsupp.degree h1
  rw [map_add, hdeg] at h2
  have h3 : (α - α').degree = 0 := by omega
  rw [Finsupp.degree_eq_zero_iff] at h3
  rw [h3, add_zero] at h1
  exact h1

lemma constantCoeff_tau (f : R) : constantCoeff (c.tau f) = residue R f := by
  rw [← coeff_zero_eq_constantCoeff_apply, coeff_tau, Dv_zero]

lemma IsCentred.map_tau_span (hc : c.IsCentred) (S : Set (Fin n)) :
    Ideal.map c.tau (Ideal.span (c.x '' S)) = Ideal.span (X '' S) := by
  rw [Ideal.map_span, ← Set.image_comp]
  congr 1
  exact Set.image_congr fun i _ => hc.tau_x i

lemma IsCentred.coeff_tau_eq_zero_of_mem (hc : c.IsCentred) {S : Set (Fin n)} {g : R}
    (hg : g ∈ Ideal.span (c.x '' S)) (δ : Fin n →₀ ℕ) (hδ : ∀ i ∈ S, δ i = 0) :
    coeff δ (c.tau g) = 0 := by
  refine coeff_eq_zero_of_mem_span_X S ?_ δ hδ
  rw [← hc.map_tau_span]
  exact Ideal.mem_map_of_mem _ hg

/-- Key step of the duality: modulo `J`, the degree-`N` part is detected by Taylor coefficients. -/
lemma IsCentred.mem_sup_pow_succ (hc : c.IsCentred) (S : Set (Fin n)) {g : R} (N : ℕ)
    (hg : g ∈ Ideal.span (c.x '' S) ⊔ maximalIdeal R ^ N)
    (h0 : ∀ δ : Fin n →₀ ℕ, (∀ i ∈ S, δ i = 0) → coeff δ (c.tau g) = 0) :
    g ∈ Ideal.span (c.x '' S) ⊔ maximalIdeal R ^ (N + 1) := by
  classical
  set J := Ideal.span (c.x '' S)
  obtain ⟨j, hj, h, hh, rfl⟩ := Submodule.mem_sup.1 hg
  rw [hc.pow_eq_span] at hh
  obtain ⟨T, hT, hhT⟩ := Submodule.mem_span_finite_of_mem_span hh
  obtain ⟨r, -, hr⟩ := (Submodule.mem_span_finset).1 hhT
  choose α hαdeg hα using fun t : T => hT t.2
  -- coefficient extraction
  have key : ∀ t : T, (∀ i ∈ S, α t i = 0) → r t ∈ maximalIdeal R := by
    intro t ht
    have h1 := h0 (α t) ht
    rw [← hr, map_add, map_add, hc.coeff_tau_eq_zero_of_mem hj _ ht, zero_add, map_sum,
      map_sum] at h1
    rw [← Finset.sum_coe_sort T] at h1
    rw [Finset.sum_eq_single t] at h1
    · have ht : c.tau (t : R) = monomial (α t) 1 := by rw [hα t]; exact hc.tau_monomial _
      rw [smul_eq_mul, map_mul, ht, coeff_mul_monomial, if_pos le_rfl,
        tsub_self, mul_one, coeff_zero_eq_constantCoeff_apply, constantCoeff_tau] at h1
      exact (residue_eq_zero_iff _).1 h1
    · intro t' _ hne
      have ht' : c.tau (t' : R) = monomial (α t') 1 := by rw [hα t']; exact hc.tau_monomial _
      rw [smul_eq_mul, map_mul, ht', coeff_mul_monomial]
      split_ifs with hle
      · exfalso
        have heq : α t' = α t :=
          Finsupp.eq_of_le_of_degree_eq hle (by rw [hαdeg, hαdeg])
        apply hne
        exact Subtype.ext (by rw [hα t', hα t, heq])
      · rfl
    · simp
  have hmem : ∀ t : T, r t • (t : R) ∈ J ⊔ maximalIdeal R ^ (N + 1) := by
    intro t
    by_cases hS : ∀ i ∈ S, α t i = 0
    · refine Ideal.mem_sup_right ?_
      rw [smul_eq_mul, pow_succ']
      refine Ideal.mul_mem_mul (key t hS) ?_
      rw [hc.pow_eq_span]
      exact Ideal.subset_span (hT t.2)
    · push_neg at hS
      obtain ⟨i, hiS, hi⟩ := hS
      refine Ideal.mem_sup_left (Ideal.mul_mem_left _ _ ?_)
      rw [hα t, ← Finset.mul_prod_erase _ _ (Finset.mem_univ i)]
      exact Ideal.mul_mem_right _ _ (Ideal.pow_mem_of_mem _
        (Ideal.subset_span (Set.mem_image_of_mem c.x hiS)) _ (Nat.pos_of_ne_zero hi))
  rw [← hr, ← Finset.sum_coe_sort T]
  exact add_mem (Ideal.mem_sup_left hj) (Ideal.sum_mem _ fun t _ => hmem t)

/-- **Relative order duality.** For a centred chart of a Noetherian local `ℚ`-algebra, an element
lies in the ideal generated by the chart functions `xᵢ`, `i ∈ S`, iff all its Taylor coefficients
at multi-indices supported off `S` vanish. -/
theorem IsCentred.mem_span_iff [IsNoetherianRing R] (hc : c.IsCentred) (S : Set (Fin n))
    (g : R) : g ∈ Ideal.span (c.x '' S) ↔
      ∀ δ : Fin n →₀ ℕ, (∀ i ∈ S, δ i = 0) → coeff δ (c.tau g) = 0 := by
  refine ⟨fun hg δ hδ => hc.coeff_tau_eq_zero_of_mem hg δ hδ, fun h0 => ?_⟩
  set J := Ideal.span (c.x '' S)
  have hN : ∀ N, g ∈ J ⊔ maximalIdeal R ^ N := by
    intro N
    induction N with
    | zero => simp
    | succ N ih => exact hc.mem_sup_pow_succ S N ih h0
  by_cases hJ : J = ⊤
  · rw [hJ]; trivial
  haveI : Nontrivial (R ⧸ J) := Ideal.Quotient.nontrivial_iff.2 hJ
  haveI : IsLocalRing (R ⧸ J) := .of_surjective' _ Ideal.Quotient.mk_surjective
  have hmax : maximalIdeal (R ⧸ J) ≠ ⊤ := (maximalIdeal.isMaximal _).ne_top
  have hbot := Ideal.iInf_pow_eq_bot_of_isLocalRing (maximalIdeal (R ⧸ J)) hmax
  rw [← Ideal.Quotient.eq_zero_iff_mem, ← Ideal.mem_bot, ← hbot, Ideal.mem_iInf]
  intro N
  have hle : Ideal.map (Ideal.Quotient.mk J) (maximalIdeal R) ≤ maximalIdeal (R ⧸ J) :=
    Ideal.map_le_iff_le_comap.2 fun r hr => by
      rw [Ideal.mem_comap, mem_maximalIdeal, mem_nonunits_iff]
      rintro ⟨u, hu⟩
      obtain ⟨s, hs⟩ := Ideal.Quotient.mk_surjective (↑u⁻¹ : R ⧸ J)
      have h1 : Ideal.Quotient.mk J (r * s) = 1 := by rw [map_mul, hs, ← hu, Units.mul_inv]
      have h2 : r * s - 1 ∈ J := by
        rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, h1, map_one, sub_self]
      have h3 : r * s - 1 ∈ maximalIdeal R := le_maximalIdeal hJ h2
      have h4 : r * s ∈ maximalIdeal R := Ideal.mul_mem_right _ _ hr
      exact (maximalIdeal.isMaximal R).ne_top ((Ideal.eq_top_iff_one _).2
        (by simpa using sub_mem h4 h3))
  have := Ideal.mem_map_of_mem (Ideal.Quotient.mk J) (hN N)
  rw [Ideal.map_sup, Ideal.map_quotient_self, bot_sup_eq, Ideal.map_pow] at this
  exact Ideal.pow_right_mono hle N this

end Chart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries IsLocalRing

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ}

namespace Chart

variable (c : Chart R n)

/-- Monomials of `w`-weight `≥ j` in the chart functions with `wᵢ ≠ 0`. -/
def wmonos (w : Fin n → ℕ) (j : ℕ) : Set R :=
  {f | ∃ α : Fin n →₀ ℕ, (∀ i, w i = 0 → α i = 0) ∧ j ≤ Finsupp.weight w α ∧
    f = ∏ i, c.x i ^ α i}

/-- The weighted monomial ideal `F_j = (x^α : ∑ wᵢ αᵢ ≥ j)`. -/
def F (w : Fin n → ℕ) (j : ℕ) : Ideal R := Ideal.span (c.wmonos w j)

lemma F_zero (w : Fin n → ℕ) : c.F w 0 = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  exact Ideal.subset_span ⟨0, fun _ _ => rfl, zero_le, by simp⟩

lemma F_antitone (w : Fin n → ℕ) {j j' : ℕ} (h : j ≤ j') : c.F w j' ≤ c.F w j :=
  Ideal.span_mono fun _ ⟨α, h0, hj, hf⟩ => ⟨α, h0, h.trans hj, hf⟩

lemma F_mul_le (w : Fin n → ℕ) (j j' : ℕ) : c.F w j * c.F w j' ≤ c.F w (j + j') := by
  rw [F, F, Ideal.span_mul_span, F]
  refine Ideal.span_mono ?_
  rintro _ ⟨a, ⟨α, h0, hj, rfl⟩, b, ⟨α', h0', hj', rfl⟩, rfl⟩
  refine ⟨α + α', fun i hi => by rw [Finsupp.add_apply, h0 i hi, h0' i hi], by rw [map_add]; omega, ?_⟩
  simp only [Finsupp.add_apply, pow_add, Finset.prod_mul_distrib]

lemma x_mem_F (w : Fin n → ℕ) (i : Fin n) (hi : w i ≠ 0) : c.x i ∈ c.F w (w i) := by
  refine Ideal.subset_span ⟨Finsupp.single i 1, fun l hl => ?_, by rw [Finsupp.weight_single, one_smul], ?_⟩
  · rw [Finsupp.single_apply]; split_ifs with h
    · subst h; exact absurd hl hi
    · rfl
  · rw [Finset.prod_eq_single i]
    · simp
    · intro l _ hl; rw [Finsupp.single_apply, if_neg (Ne.symm hl), pow_zero]
    · simp

end Chart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries IsLocalRing

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ} [IsLocalRing R] {c : Chart R n}

omit [CommRing R] [Algebra ℚ R] [IsLocalRing R] in
lemma weight_le_of_le (w : Fin n → ℕ) {β β' : Fin n →₀ ℕ} (h : β' ≤ β) :
    Finsupp.weight w β' ≤ Finsupp.weight w β := by
  have : β' + (β - β') = β := add_tsub_cancel_of_le h
  rw [← this, map_add]; exact Nat.le_add_right _ _

omit [CommRing R] [Algebra ℚ R] [IsLocalRing R] in
lemma eq_zero_of_weight_eq_zero (w : Fin n → ℕ) {γ : Fin n →₀ ℕ}
    (hs : ∀ i, w i = 0 → γ i = 0) (hw : Finsupp.weight w γ = 0) : γ = 0 := by
  rw [Finsupp.weight_eq_sum, Finset.sum_eq_zero_iff] at hw
  ext i
  by_cases hi : w i = 0
  · exact hs i hi
  · have := hw i (Finset.mem_univ _)
    rw [smul_eq_mul, mul_eq_zero] at this
    exact this.resolve_right hi

namespace Chart

lemma IsCentred.map_tau_F (hc : c.IsCentred) (w : Fin n → ℕ) (j : ℕ) :
    Ideal.map c.tau (c.F w j) =
      Ideal.span ((fun α => monomial α 1) ''
        {α : Fin n →₀ ℕ | (∀ i, w i = 0 → α i = 0) ∧ j ≤ Finsupp.weight w α}) := by
  rw [F, Ideal.map_span]
  congr 1
  ext Φ; constructor
  · rintro ⟨f, ⟨α, h0, hj, rfl⟩, rfl⟩
    exact ⟨α, ⟨h0, hj⟩, (hc.tau_monomial α).symm⟩
  · rintro ⟨α, ⟨h0, hj⟩, rfl⟩
    exact ⟨_, ⟨α, h0, hj, rfl⟩, hc.tau_monomial α⟩

lemma coeff_eq_zero_of_mem_span_monomial {K : Type*} [CommRing K] (w : Fin n → ℕ) (j : ℕ)
    {Φ : MvPowerSeries (Fin n) K}
    (hΦ : Φ ∈ Ideal.span ((fun α => monomial α (1 : K)) ''
        {α : Fin n →₀ ℕ | (∀ i, w i = 0 → α i = 0) ∧ j ≤ Finsupp.weight w α}))
    (β : Fin n →₀ ℕ) (hβ : Finsupp.weight w β < j) : coeff β Φ = 0 := by
  classical
  revert β
  induction hΦ using Submodule.span_induction with
  | mem Ψ hΨ =>
    intro β hβ
    obtain ⟨α, ⟨_, hj⟩, rfl⟩ := hΨ
    rw [coeff_monomial, if_neg]
    rintro rfl; omega
  | zero => intros; simp
  | add _ _ _ _ h1 h2 => intro β hβ; rw [map_add, h1 β hβ, h2 β hβ, add_zero]
  | smul a Ψ _ h =>
    intro β hβ
    rw [smul_eq_mul, coeff_mul, Finset.sum_eq_zero]
    intro p hp
    rw [Finset.HasAntidiagonal.mem_antidiagonal] at hp
    have hle : p.2 ≤ β := hp ▸ le_add_self
    rw [h p.2 (lt_of_le_of_lt (weight_le_of_le w hle) hβ), mul_zero]

/-- **Weighted duality.** For a centred chart, `g ∈ F_j(w)` iff all Taylor coefficients of `g`
of `w`-weight `< j` vanish. -/
theorem IsCentred.mem_F_iff [IsNoetherianRing R] (hc : c.IsCentred) (w : Fin n → ℕ) :
    ∀ (j : ℕ) (g : R), g ∈ c.F w j ↔
      ∀ β : Fin n →₀ ℕ, Finsupp.weight w β < j → coeff β (c.tau g) = 0 := by
  classical
  intro j
  induction j with
  | zero => intro g; simp [F_zero]
  | succ j ih =>
    intro g
    constructor
    · intro hg β hβ
      refine coeff_eq_zero_of_mem_span_monomial w (j + 1) ?_ β hβ
      rw [← hc.map_tau_F]
      exact Ideal.mem_map_of_mem _ hg
    · intro h0
      have hg : g ∈ c.F w j := (ih g).2 fun β hβ => h0 β (by omega)
      obtain ⟨T, hT, hgT⟩ := Submodule.mem_span_finite_of_mem_span hg
      obtain ⟨r, -, hr⟩ := (Submodule.mem_span_finset).1 hgT
      choose α hα0 hαj hα using fun t : T => hT t.2
      have hmem : ∀ t : T, r t • (t : R) ∈ c.F w (j + 1) := by
        intro t
        by_cases hlt : j + 1 ≤ Finsupp.weight w (α t)
        · exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨α t, hα0 t, hlt, hα t⟩)
        · have heq : Finsupp.weight w (α t) = j := by have := hαj t; omega
          -- `r t` lies in the ideal of the centre
          have hrt : r t ∈ Ideal.span (c.x '' {i | w i ≠ 0}) := by
            rw [hc.mem_span_iff]
            intro δ hδ
            have hδw : Finsupp.weight w δ = 0 := by
              rw [Finsupp.weight_eq_sum, Finset.sum_eq_zero_iff]
              intro i _
              by_cases hi : w i = 0
              · rw [hi, smul_zero]
              · rw [hδ i hi, zero_smul]
            have h1 := h0 (α t + δ) (by rw [map_add, heq, hδw]; omega)
            rw [← hr, map_sum, map_sum, ← Finset.sum_coe_sort T, Finset.sum_eq_single t] at h1
            · have ht : c.tau (t : R) = monomial (α t) 1 := by
                rw [hα t]; exact hc.tau_monomial _
              rwa [smul_eq_mul, map_mul, ht, coeff_mul_monomial, if_pos le_self_add,
                add_tsub_cancel_left, mul_one] at h1
            · intro t' _ hne
              have ht' : c.tau (t' : R) = monomial (α t') 1 := by
                rw [hα t']; exact hc.tau_monomial _
              rw [smul_eq_mul, map_mul, ht', coeff_mul_monomial]
              split_ifs with hle
              · exfalso
                have hle' : α t' ≤ α t := by
                  intro i
                  have := hle i
                  simp only [Finsupp.coe_add, Pi.add_apply] at this
                  by_cases hi : w i = 0
                  · rw [hα0 t' i hi]; exact Nat.zero_le _
                  · rw [hδ i hi, add_zero] at this; exact this
                have hsub := add_tsub_cancel_of_le hle'
                have hw := congrArg (Finsupp.weight w) hsub
                rw [map_add, heq] at hw
                have hw0 : Finsupp.weight w (α t - α t') = 0 := by have := hαj t'; omega
                have hz := eq_zero_of_weight_eq_zero w (fun i hi => by
                  simp only [Finsupp.coe_tsub, Pi.sub_apply, hα0 t i hi, Nat.zero_sub]) hw0
                rw [hz, add_zero] at hsub
                exact hne (Subtype.ext (by rw [hα t', hα t, hsub]))
              · rfl
            · simp
          -- conclude
          rw [smul_eq_mul]
          have aux : ∀ y ∈ Ideal.span (c.x '' {i | w i ≠ 0}), y * (t : R) ∈ c.F w (j + 1) := by
            intro y hy
            induction hy using Submodule.span_induction with
            | mem y hy =>
              obtain ⟨i, hi, rfl⟩ := hy
              refine Ideal.subset_span ⟨α t + Finsupp.single i 1, fun l hl => ?_, ?_, ?_⟩
              · rw [Finsupp.add_apply, hα0 t l hl, Finsupp.single_apply,
                  if_neg (by rintro rfl; exact hi hl), add_zero]
              · rw [map_add, heq, Finsupp.weight_single, one_smul]
                have : w i ≠ 0 := hi
                omega
              · rw [prod_pow_add_single, hα t, mul_comm]
            | zero => rw [zero_mul]; exact zero_mem _
            | add _ _ _ _ h1 h2 => rw [add_mul]; exact add_mem h1 h2
            | smul a y _ h => rw [smul_eq_mul, mul_assoc]; exact Ideal.mul_mem_left _ _ h
          exact aux _ hrt
      rw [← hr, ← Finset.sum_coe_sort T]
      exact Ideal.sum_mem _ fun t _ => hmem t

end Chart

end BezoutCounterexample.Principalization
